import type { ItemType, ItemTypeDef, StaffConfig } from '../types';

export const ITEM_TYPES: ItemTypeDef[] = [
  { id: 'staff', name: '杖', nameEn: 'Staff', icon: 'staff', patch: { shaftLength: 0.88, shaftThickness: 0.062, shaftAngle: -48, headSize: 0.3, collarStyle: 'filigree', pommelStyle: 'gem', prongs: 3, shaftStyle: 'royal', wrapStyle: 'spiral', shaftCurve: 0.04, tipStyle: 'gem-cluster', gemCut: 'brilliant', gemMount: 'claw', gemCount: 5, adornmentStyle: 'filigree', adornmentDensity: 0.76 }, desc: '古典的な長杖 · 花咲く宝石冠と彫金' },
  { id: 'rod', name: 'ロッド', nameEn: 'Rod', icon: 'rod', patch: { shaftLength: 0.9, shaftThickness: 0.028, shaftAngle: -40, headSize: 0.14, collarStyle: 'ring', pommelStyle: 'cap', prongs: 0, shaftStyle: 'straight', wrapStyle: 'none', shaftCurve: 0, headShape: 'orb', tipStyle: 'floating-gem', gemCut: 'emerald', gemMount: 'floating', gemCount: 2, adornmentStyle: 'star-map', adornmentDensity: 0.34 }, desc: '極細の魔導ロッド · 浮遊する核と星図' },
  { id: 'wand', name: 'ワンド', nameEn: 'Wand', icon: 'wand', patch: { shaftLength: 0.6, shaftThickness: 0.046, shaftAngle: -38, headSize: 0.24, collarStyle: 'none', pommelStyle: 'cap', prongs: 2, shaftStyle: 'straight', wrapStyle: 'none', shaftCurve: 0, tipStyle: 'star', gemCut: 'star-cut', gemMount: 'claw', gemCount: 1, adornmentStyle: 'rune-engraving', adornmentDensity: 0.52 }, desc: '短い指揮棒 · 星灯りのルーン彫刻' },
  { id: 'scepter', name: 'セプター', nameEn: 'Scepter', icon: 'scepter', patch: { shaftLength: 0.58, shaftThickness: 0.072, shaftAngle: -34, headSize: 0.27, collarStyle: 'crown', pommelStyle: 'gem', prongs: 0, shaftStyle: 'royal', wrapStyle: 'spiral', shaftCurve: 0, tipStyle: 'lotus-crown', gemCut: 'emerald', gemMount: 'bezel', gemCount: 7, adornmentStyle: 'gold-pave', adornmentDensity: 0.82 }, desc: '王家の笏 · 宝石を抱く蓮華冠' },
  { id: 'cane', name: 'ステッキ', nameEn: 'Cane', icon: 'cane', patch: { shaftLength: 0.76, shaftThickness: 0.05, shaftAngle: -56, headSize: 0.17, collarStyle: 'ring', pommelStyle: 'cap', prongs: 0, shaftStyle: 'leather', wrapStyle: 'stitch', shaftCurve: 0.13, tipStyle: 'none', gemCut: 'cabochon', gemMount: 'bezel', gemCount: 1, adornmentStyle: 'chain-drape', adornmentDensity: 0.32 }, desc: '湾曲した柄 · 革巻きと懐中時計風の金具' },
  { id: 'trident', name: 'トライデント', nameEn: 'Trident', icon: 'trident', patch: { shaftLength: 0.88, shaftThickness: 0.055, shaftAngle: -58, headSize: 0.2, collarStyle: 'guard', pommelStyle: 'spike', prongs: 3, shaftStyle: 'coral', wrapStyle: 'scale', shaftCurve: 0, tipStyle: 'triple-prong', gemCut: 'marquise', gemMount: 'cage', gemCount: 3, adornmentStyle: 'geodesic', adornmentDensity: 0.62 }, desc: '三叉の海神槍 · 珊瑚と真珠の冠' },
  { id: 'scythe', name: '鎌', nameEn: 'Scythe', icon: 'scythe', patch: { shaftLength: 0.94, shaftThickness: 0.042, shaftAngle: -62, headSize: 0.2, collarStyle: 'skull-collar', pommelStyle: 'anchor', prongs: 0, shaftStyle: 'bone', wrapStyle: 'thorn', shaftCurve: 0, tipStyle: 'void-crown', gemCut: 'rose-cut', gemMount: 'halo', gemCount: 2, adornmentStyle: 'thorn-vine', adornmentDensity: 0.68 }, desc: '大鎌 · 黒薔薇と髑髏の護環' },
  { id: 'crosier', name: '司教杖', nameEn: 'Crosier', icon: 'crosier', patch: { shaftLength: 0.84, shaftThickness: 0.055, shaftAngle: -50, headSize: 0.19, collarStyle: 'wing-guard', pommelStyle: 'gem', prongs: 0, shaftStyle: 'ivory', wrapStyle: 'rune-band', shaftCurve: -0.11, tipStyle: 'moon-circlet', gemCut: 'rose-cut', gemMount: 'petal', gemCount: 5, adornmentStyle: 'rune-engraving', adornmentDensity: 0.72 }, desc: '巻き矢じり · 聖花と祈祷ルーンの司教杖' },
  { id: 'grimoire', name: '魔道書', nameEn: 'Grimoire', icon: 'grimoire', patch: { shaftLength: 0.3, shaftThickness: 0.03, shaftAngle: -20, headSize: 0.42, collarStyle: 'none', pommelStyle: 'none', prongs: 0, shaftStyle: 'leather', wrapStyle: 'none', shaftCurve: 0, headShape: 'tome', tipStyle: 'none', dangleStyle: 'ribbon', dangleCount: 2, gemCut: 'opal', gemMount: 'bezel', gemCount: 3, adornmentStyle: 'rune-engraving', adornmentDensity: 0.62 }, desc: '携える書物 · 星座の銀箔と宝石留め具' },
  { id: 'focus-orb', name: '魔導球', nameEn: 'Focus Orb', icon: 'focus-orb', patch: { shaftLength: 0.22, shaftThickness: 0.026, shaftAngle: -30, headSize: 0.44, collarStyle: 'orb-cage', pommelStyle: 'none', prongs: 4, shaftStyle: 'techno', wrapStyle: 'none', shaftCurve: 0, headShape: 'orb', tipStyle: 'celestial-cage', orbiterStyle: 'prism-ring', orbiterCount: 6, gemCut: 'prism', gemMount: 'cage', gemCount: 6, adornmentStyle: 'geodesic', adornmentDensity: 0.9 }, desc: '魔導焦点球 · 六重ジオデシック檻と衛星宝石' },
  { id: 'censer', name: '香炉', nameEn: 'Censer', icon: 'censer', patch: { shaftLength: 0.52, shaftThickness: 0.032, shaftAngle: -66, headSize: 0.3, collarStyle: 'ring', pommelStyle: 'ring', prongs: 0, shaftStyle: 'chain-link', wrapStyle: 'chain', shaftCurve: 0, headShape: 'chalice', tipStyle: 'none', dangleStyle: 'chain-charm', dangleCount: 3, particleStyle: 'ash', gemCut: 'cabochon', gemMount: 'cage', gemCount: 2, adornmentStyle: 'chain-drape', adornmentDensity: 0.7 }, desc: '吊るす香炉 · 細鎖と燻る宝石' },
  { id: 'bell', name: '鈴杖', nameEn: 'Bell Staff', icon: 'bell', patch: { shaftLength: 0.8, shaftThickness: 0.05, shaftAngle: -52, headSize: 0.22, collarStyle: 'ring', pommelStyle: 'cap', prongs: 0, shaftStyle: 'braided', wrapStyle: 'ribbon', shaftCurve: 0.05, tipStyle: 'bell', dangleStyle: 'bell', dangleCount: 3, particleStyle: 'musical', gemCut: 'rose-cut', gemMount: 'bezel', gemCount: 3, adornmentStyle: 'filigree', adornmentDensity: 0.56 }, desc: '鈴の音色 · 螺鈿と浮かぶ音符の巡礼杖' },
  { id: 'talisman', name: '護符', nameEn: 'Talisman', icon: 'talisman', patch: { shaftLength: 0.26, shaftThickness: 0.022, shaftAngle: -70, headSize: 0.36, collarStyle: 'ring', pommelStyle: 'none', prongs: 0, shaftStyle: 'chain-link', wrapStyle: 'none', shaftCurve: 0, headShape: 'ankh', tipStyle: 'none', dangleStyle: 'beads', dangleCount: 2, gemCut: 'opal', gemMount: 'bezel', gemCount: 3, adornmentStyle: 'star-map', adornmentDensity: 0.44 }, desc: '護符ペンダント · 七星と数珠の封印' },
  { id: 'spear', name: '魔槍', nameEn: 'Spear', icon: 'spear', patch: { shaftLength: 0.96, shaftThickness: 0.038, shaftAngle: -60, headSize: 0.16, collarStyle: 'guard', pommelStyle: 'anchor', prongs: 0, shaftStyle: 'straight', wrapStyle: 'wire', shaftCurve: 0, tipStyle: 'blade', gemCut: 'marquise', gemMount: 'claw', gemCount: 2, adornmentStyle: 'gold-pave', adornmentDensity: 0.32 }, desc: '長柄の穂先 · 鍛造された刃と宝石鋲' },
  { id: 'lantern-pole', name: '提灯杖', nameEn: 'Lantern Pole', icon: 'lantern-pole', patch: { shaftLength: 0.82, shaftThickness: 0.042, shaftAngle: -54, headSize: 0.2, collarStyle: 'ring', pommelStyle: 'cap', prongs: 0, shaftStyle: 'bamboo', wrapStyle: 'none', shaftCurve: 0.18, tipStyle: 'lantern', dangleStyle: 'ribbon', dangleCount: 2, gemGlow: 0.9, outerGlow: 0.75, adornmentStyle: 'none' }, desc: '静かに揺れる灯籠 · 暖かな灯火' },
  { id: 'brush', name: '筆', nameEn: 'Calligraphy Brush', icon: 'brush', patch: { shaftLength: 0.72, shaftThickness: 0.028, shaftAngle: -36, headSize: 0.13, collarStyle: 'ring', pommelStyle: 'cap', prongs: 0, shaftStyle: 'porcelain', wrapStyle: 'none', shaftCurve: 0, tipStyle: 'prism-trio', outerGlow: 0.4, finish: 'glossy', adornmentStyle: 'none' }, desc: '魔書を刻む筆 · 黒い筆先と白磁柄' },
  { id: 'mace', name: '魔球鎚', nameEn: 'Orb Mace', icon: 'mace', patch: { shaftLength: 0.78, shaftThickness: 0.06, shaftAngle: -46, headSize: 0.27, collarStyle: 'guard', pommelStyle: 'anchor', prongs: 0, shaftStyle: 'alloy', wrapStyle: 'scale', shaftCurve: 0, tipStyle: 'gem-cluster', prongColor: '#c8c8c8', outerGlow: 0.5, finish: 'metallic', adornmentStyle: 'gold-pave', adornmentDensity: 0.42 }, desc: '大きな宝珠の鎚頭 · 重厚な打撃具' },
  { id: 'chain-flail', name: '鎖鎚杖', nameEn: 'Chain Flail Staff', icon: 'chain-flail', patch: { shaftLength: 0.8, shaftThickness: 0.032, shaftAngle: -62, headSize: 0.18, collarStyle: 'ring', pommelStyle: 'anchor', prongs: 0, shaftStyle: 'chain-link', wrapStyle: 'wire', shaftCurve: 0, tipStyle: 'snow-globe-tip', dangleStyle: 'chain-charm', dangleCount: 3, outerGlow: 0.3, finish: 'metallic', adornmentStyle: 'chain-drape', adornmentDensity: 0.5 }, desc: '鎖と迫力ある鉄球 · 揺れる運動感' },

  /* ── 型に囚われない: 柄のない浮遊遺物 ── */
  { id: 'relic', name: '浮遊遺物', nameEn: 'Floating Relic', icon: 'relic', patch: { shaftLength: 0, shaftThickness: 0.02, shaftAngle: -45, headSize: 0.34, collarStyle: 'none', pommelStyle: 'none', prongs: 0, wrapStyle: 'none', shaftCurve: 0, tipStyle: 'orbit-ring', orbiterStyle: 'gem-set', orbiterCount: 4, halo: 'triple', adornmentStyle: 'star-map', adornmentDensity: 0.7, outerGlow: 0.8 }, desc: '柄なき遺物 · 空に浮かぶ宝石と星図' },
  { id: 'signet', name: '印章指輪', nameEn: 'Signet Ring', icon: 'signet', patch: { shaftLength: 0, shaftThickness: 0.02, shaftAngle: -45, headSize: 0.26, collarStyle: 'none', pommelStyle: 'none', prongs: 0, wrapStyle: 'none', shaftCurve: 0, tipStyle: 'gem', gemMount: 'bezel', gemCut: 'cabochon', gemCount: 2, adornmentStyle: 'filigree', adornmentDensity: 0.55, finish: 'metallic' }, desc: '金の輪に据えた宝石 · 小さな紋章' },
  { id: 'monolith', name: '結晶碑', nameEn: 'Crystal Monolith', icon: 'monolith', patch: { shaftLength: 0, shaftThickness: 0.02, shaftAngle: -90, headSize: 0.42, collarStyle: 'none', pommelStyle: 'none', prongs: 0, wrapStyle: 'none', shaftCurve: 0, headShape: 'cluster', tipStyle: 'crystal-tip', adornmentStyle: 'geodesic', adornmentDensity: 0.5, finish: 'glossy' }, desc: '林立する巨大晶簇 · 柄を持たない碑' },
  { id: 'orb-solo', name: '単独宝珠', nameEn: 'Lone Orb', icon: 'orb-solo', patch: { shaftLength: 0, shaftThickness: 0.02, shaftAngle: -45, headSize: 0.4, collarStyle: 'none', pommelStyle: 'none', prongs: 0, wrapStyle: 'none', shaftCurve: 0, headShape: 'orb', tipStyle: 'none', gemMount: 'floating', innerStyle: 'galaxy', orbiterStyle: 'pearl', orbiterCount: 3, outerGlow: 0.85 }, desc: 'ただ一つの宝珠 · 内なる銀河' },
  { id: 'pennant', name: '御旗', nameEn: 'Pennant', icon: 'pennant', patch: { shaftLength: 0, shaftThickness: 0.02, shaftAngle: -45, headSize: 0.38, collarStyle: 'none', pommelStyle: 'none', prongs: 0, wrapStyle: 'none', shaftCurve: 0, headShape: 'banner', tipStyle: 'none', dangleStyle: 'ribbon', dangleCount: 3, finish: 'matte' }, desc: '翻る布の旗 · 紋章と房飾り' },
  { id: 'idol', name: '小偶像', nameEn: 'Idol', icon: 'idol', patch: { shaftLength: 0, shaftThickness: 0.02, shaftAngle: -45, headSize: 0.36, collarStyle: 'none', pommelStyle: 'none', prongs: 0, wrapStyle: 'none', shaftCurve: 0, headShape: 'totem', tipStyle: 'none', adornmentStyle: 'gold-pave', adornmentDensity: 0.6, finish: 'lacquered' }, desc: '不死のトーテム · 金緑の偶像' },
  { id: 'chime', name: '風鈴', nameEn: 'Wind Chime', icon: 'chime', patch: { shaftLength: 0, shaftThickness: 0.02, shaftAngle: -45, headSize: 0.3, collarStyle: 'bell-dome', pommelStyle: 'none', prongs: 0, wrapStyle: 'none', shaftCurve: 0, headShape: 'brazier', tipStyle: 'none', dangleStyle: 'bell', dangleCount: 4, particleStyle: 'musical', motif: 'notes', motifIntensity: 0.7 }, desc: '鈴と短冊が揺れる風鈴' },
];

export const getItemType = (id: ItemType): ItemTypeDef => ITEM_TYPES.find((t) => t.id === id) || ITEM_TYPES[0];
export const applyItemType = (id: ItemType): Partial<StaffConfig> => getItemType(id).patch;
