import type { AnimationDef, EffectPreset, Preset } from '../types';

/* ══════════ アニメーション定義 ══════════ */
export const ANIMATIONS: AnimationDef[] = [
  { id: 'none', name: '静止', en: 'Static', desc: 'アニメーションなし・単一フレーム。', frames: 1, fps: 20, needs: {} },
  { id: 'enchant-glint', name: 'エンチャント', en: 'Enchant Glint', desc: 'バニラのエンチャント風の紫のグリントが斜めに流れる。', frames: 16, fps: 20, needs: { finish: 'glossy' } },
  { id: 'pulse-glow', name: '脈動オーラ', en: 'Pulsing Aura', desc: '外側の光が鼓動のように明滅。', frames: 12, fps: 20, needs: {} },
  { id: 'orbit', name: '浮遊物公転', en: 'Orbiters', desc: '周囲の浮遊物が頭部を公転する。', frames: 20, fps: 20, needs: { orbiterCount: 4 } },
  { id: 'float', name: '浮遊揺れ', en: 'Bob & Sway', desc: '杖全体がゆっくり上下し、微少回転する。', frames: 24, fps: 20, needs: {} },
  { id: 'flame-flicker', name: '炎ゆらぎ', en: 'Flame Flicker', desc: '炎の輝き・火の粉がゆらめき立ち上がる。', frames: 14, fps: 20, needs: { element: 'fire' } },
  { id: 'lightning-arc', name: '雷光', en: 'Lightning Arc', desc: '稲妻のアークが不規則にフラッシュ。', frames: 10, fps: 30, needs: { element: 'lightning', motif: 'bolt', motifIntensity: 1 } },
  { id: 'frost-shimmer', name: '霜の煌めき', en: 'Frost Shimmer', desc: '霜の粒子が明滅し、表面のキラキラが移動。', frames: 16, fps: 20, needs: { element: 'ice' } },
  { id: 'spin-gem', name: '宝珠回転', en: 'Gem Spin', desc: '宝珠の内部の渦が回転し、キラッと反射。', frames: 18, fps: 24, needs: { innerStyle: 'swirl' } },
  { id: 'rainbow-core', name: '虹色コア', en: 'Rainbow Core', desc: '宝石の内側が色相環を一周。', frames: 24, fps: 18, needs: { innerStyle: 'core' } },
  { id: 'holy-rays', name: '聖光回転', en: 'Rotating Rays', desc: 'サンバーストの光線がゆっくり回る。', frames: 20, fps: 20, needs: { halo: 'sunburst' } },
  { id: 'bubbles-rise', name: '気泡上昇', en: 'Rising Bubbles', desc: '気泡のパーティクルがゆっくり上に流れる。', frames: 18, fps: 20, needs: { element: 'water', particleStyle: 'bubbles' } },
  { id: 'petal-drift', name: '花びら舞い', en: 'Petal Drift', desc: '花びら/葉が風で舞い落ちる。', frames: 22, fps: 20, needs: { particleStyle: 'leaf', particles: 12 } },
  { id: 'void-breath', name: '闇の呼吸', en: 'Void Breath', desc: '虚無の靄がゆっくり吸気/呼気。', frames: 24, fps: 15, needs: { element: 'void', motif: 'wisp' } },
  { id: 'ember-swirl', name: '火の粉螺旋', en: 'Ember Swirl', desc: '火の粉が螺旋を描いて上昇。', frames: 16, fps: 24, needs: { element: 'fire', particleStyle: 'embers' } },
  { id: 'rune-pulse', name: 'ルーン鼓動', en: 'Runic Pulse', desc: 'ルーン・バンドのルーンが順に脈打つ。', frames: 14, fps: 20, needs: { wrapStyle: 'rune-band' } },
  { id: 'wings-flap', name: '羽ばたき', en: 'Wing Flap', desc: '翼がゆっくり羽ばたく。', frames: 16, fps: 18, needs: { wings: 'angel' } },
  { id: 'heartbeat', name: '鼓動', en: 'Heartbeat', desc: '光が二度打つように脈動する。', frames: 16, fps: 16, needs: { outerGlow: 0.8 } },
  { id: 'shimmer-wave', name: '揺光', en: 'Shimmer Wave', desc: '宝石の色がゆったり虹へゆれる。', frames: 20, fps: 18, needs: { innerStyle: 'galaxy' } },
  { id: 'chromatic-drift', name: '彩流', en: 'Chromatic Drift', desc: '色相が静かに一周を巡る。', frames: 24, fps: 16, needs: {} },
  { id: 'clock-tick', name: '時計', en: 'Clockwork', desc: '刻みながら牙車や宝珠が回る。', frames: 12, fps: 10, needs: { orbiterStyle: 'gear' } },
  { id: 'sparkle-cascade', name: '星瀑', en: 'Sparkle Cascade', desc: '星屑が尾を引いて流れ落ちる。', frames: 16, fps: 18, needs: { particleStyle: 'mixed' } },
  { id: 'sakura-fall', name: '花吹雪', en: 'Sakura Fall', desc: '花びらが静かに舞い降りる。', frames: 22, fps: 14, needs: { particleStyle: 'leaf', particles: 14 } },
];

/* ══════════ エフェクトプリセット ══════════ */
/** Measured directly from the Azisaba "life" pack: hard alpha, 11–22% fill, ~30–60 colours, dark single-hue shafts. */
export const LIFE_AUTHENTIC: Partial<import('../types').StaffConfig> = {
  resolution: 32, refined: true, softEdge: false, paletteSize: 0,
  shaftLength: 0.92, shaftThickness: 0.030, shaftAngle: -44, shaftCurve: 0.03,
  shaftStyle: 'straight', shaftDetail: 0.5, grain: 0.18,
  headSize: 0.17, prongs: 0, particles: 3, particleStyle: 'dots',
  outerGlow: 0.18, gemGlow: 0.45, dither: false, shading: 0.85,
  contrast: 1.18, outline: 'dark', finish: 'glossy',
  motif: 'none', motifIntensity: 0, motif2: 'none',
  wings: 'none', halo: 'none', orbiterStyle: 'none', dangleStyle: 'none',
  adornmentStyle: 'none', wearStyle: 'none',
};

export const EFFECT_PRESETS: EffectPreset[] = [
  { name: '静穏な宝石光', nameEn: 'Restrained Jewel Light', icon: 'gem', patch: { outerGlow: 0.16, gemGlow: 0.55, particles: 4, halo: 'none', dropShadow: false, motifIntensity: 0.2, motif2: 'none', contrast: 1.08, finish: 'glossy' } },
  {
    name: 'Life鯖オーセンティック', nameEn: 'Azisaba Life Authentic', icon: 'square',
    patch: {
      ...LIFE_AUTHENTIC,
      harmony: 'monochrome', paletteSize: 48,
      wrapStyle: 'rings', wrapDensity: 9,
      collarStyle: 'ring', pommelStyle: 'cap', tipStyle: 'gem',
      motif: 'none', motifIntensity: 0,
    },
  },
  { name: 'エンチャント輝き', nameEn: 'Enchanted Glint', icon: 'sparkles', patch: { finish: 'enchanted', outerGlow: 0.6, dither: true, particleStyle: 'sparkle', particles: 10, outline: 'selout', shading: 0.8, contrast: 1.12, grain: 0.2, motif: 'rune', motifIntensity: 0.55 } },
  { name: '業火の軌跡', nameEn: 'Ember Trail', icon: 'flame', patch: { element: 'fire', particleStyle: 'embers', particles: 16, outerGlow: 0.88, finish: 'glossy', motif: 'flame', motifIntensity: 0.95, outline: 'colored', shading: 0.7 } },
  { name: '氷結のオーラ', nameEn: 'Frost Aura', icon: 'snowflake', patch: { element: 'ice', particleStyle: 'diamonds', particles: 12, outerGlow: 0.5, finish: 'glossy', motif: 'frost', motifIntensity: 0.8, halo: 'ring', outline: 'light', shading: 0.85 } },
  { name: '雷撃の脈動', nameEn: 'Arc Pulse', icon: 'zap', patch: { element: 'lightning', particleStyle: 'mixed', particles: 14, outerGlow: 0.72, finish: 'metallic', motif: 'bolt', motifIntensity: 0.9, halo: 'double', outline: 'dark', shading: 0.9 } },
  { name: '聖なる光', nameEn: 'Divine Rays', icon: 'sun', patch: { element: 'light', particleStyle: 'plus', particles: 12, outerGlow: 0.85, finish: 'metallic', motif: 'rays', motifIntensity: 1, halo: 'sunburst', outline: 'gold', shading: 0.8 } },
  { name: '虚無の霧', nameEn: 'Void Mist', icon: 'orbit', patch: { element: 'void', particleStyle: 'dots', particles: 14, outerGlow: 0.78, finish: 'matte', motif: 'void', motifIntensity: 0.85, halo: 'eclipse', outline: 'colored', shading: 0.6, contrast: 1.05 } },
  { name: '神秘のルーン', nameEn: 'Arcane Runes', icon: 'rune', patch: { motif: 'rune', motifIntensity: 1, particleStyle: 'sparkle', particles: 12, outerGlow: 0.6, halo: 'rune-ring', finish: 'enchanted', outline: 'selout', shading: 0.75 } },
  { name: '血の儀式', nameEn: 'Blood Ritual', icon: 'droplet', patch: { element: 'blood', particleStyle: 'embers', particles: 11, outerGlow: 0.65, finish: 'weathered', motif: 'drip', motifIntensity: 0.8, outline: 'dark', shading: 0.7, contrast: 1.15 } },
  { name: '職人の質素仕上げ', nameEn: 'Humble Artisan', icon: 'hammer', patch: { finish: 'matte', outerGlow: 0.1, particles: 3, dither: false, shading: 0.5, contrast: 0.95, grain: 0.55, outline: 'dark', motif: 'none', motifIntensity: 0 } },
  { name: '高級装飾', nameEn: 'Opulent Regalia', icon: 'crown', patch: { finish: 'metallic', outerGlow: 0.55, halo: 'double', particles: 10, particleStyle: 'diamonds', collarStyle: 'filigree', pommelStyle: 'gem', contrast: 1.16, outline: 'gold', shading: 0.85, motif: 'rune', motifIntensity: 0.4 } },
  { name: 'ミニマル・クラシック', nameEn: 'Minimal Classic', icon: 'square', patch: { resolution: 16, refined: false, outerGlow: 0.2, particles: 4, particleStyle: 'dots', dither: false, outline: 'dark', finish: 'matte', shading: 0.6, contrast: 1, motif: 'none', motifIntensity: 0, shaftDetail: 0.2 } },
  { name: '月光のきらめき', nameEn: 'Moonlight Sheen', icon: 'moon', patch: { element: 'dark', particleStyle: 'sparkle', particles: 9, outerGlow: 0.6, finish: 'glossy', motif: 'wisp', motifIntensity: 0.7, halo: 'eclipse', outline: 'light', shading: 0.8, contrast: 1.08 } },
];

/* ══════════ マスターコレクション ══════════ */
export const PRESETS: Preset[] = [
  { name: 'Archmage Sovereign', tagline: 'Royal violet orb · gold filigree', icon: 'crown', accent: '#7c3aed',
    config: { element: 'arcane', itemType: 'staff', headShape: 'orb', gemColor: '#7c3aed', gemColor2: '#22d3ee', glowColor: '#7c3aed', shaftStyle: 'royal', shaftColor: '#4a2c17', shaftColor2: '#241408', wrapStyle: 'spiral', wrapColor: '#d4af37', collarStyle: 'filigree', collarColor: '#d4af37', prongs: 3, halo: 'rune-ring', haloColor: '#ffd700', particles: 12, particleStyle: 'sparkle', outerGlow: 0.6, finish: 'enchanted', wings: 'none', pommelStyle: 'gem', tipStyle: 'gem', motif: 'rune', motifIntensity: 0.5 } },
  { name: 'Inferno Tyrant', tagline: 'Molten crystal · ember storm', icon: 'flame', accent: '#ef4444',
    config: { element: 'fire', itemType: 'staff', headShape: 'crystal', gemColor: '#ef4444', gemColor2: '#f59e0b', glowColor: '#f97316', shaftStyle: 'gnarled', shaftColor: '#2b1a12', shaftColor2: '#120905', wrapStyle: 'chain', wrapColor: '#7c2d12', collarStyle: 'claw', collarColor: '#b87333', prongs: 4, particles: 16, particleStyle: 'embers', outerGlow: 0.85, finish: 'glossy', horns: true, hornColor: '#3f1d12', pommelStyle: 'spike', tipStyle: 'flame', motif: 'flame', motifIntensity: 0.9 } },
  { name: 'Frost Sovereign', tagline: 'Glacial diamond · seraph wings', icon: 'snowflake', accent: '#0ea5e9',
    config: { element: 'ice', itemType: 'staff', headShape: 'diamond', gemColor: '#7dd3fc', gemColor2: '#f0f9ff', glowColor: '#38bdf8', shaftStyle: 'straight', shaftColor: '#dbeafe', shaftColor2: '#64748b', wrapStyle: 'rings', wrapColor: '#0ea5e9', collarStyle: 'guard', collarColor: '#c0c0c0', prongs: 2, wings: 'angel', wingColor: '#e0f2fe', particles: 10, particleStyle: 'diamonds', outerGlow: 0.5, finish: 'glossy', pommelStyle: 'cap', innerStyle: 'facet', tipStyle: 'crystal-tip', motif: 'frost', motifIntensity: 0.75, halo: 'ring', haloColor: '#bae6fd' } },
  { name: 'Verdant Warden', tagline: 'Bloom heart · living vine', icon: 'leaf', accent: '#22c55e',
    config: { element: 'nature', itemType: 'staff', headShape: 'bloom', gemColor: '#22c55e', gemColor2: '#fde68a', glowColor: '#4ade80', shaftStyle: 'gnarled', shaftColor: '#4d3b28', shaftColor2: '#241a10', wrapStyle: 'vine', wrapColor: '#4ade80', collarStyle: 'none', collarColor: '#84cc16', prongs: 0, particles: 8, particleStyle: 'leaf', outerGlow: 0.4, finish: 'matte', pommelStyle: 'ring', innerStyle: 'core', tipStyle: 'cluster', motif: 'leaf', motifIntensity: 0.7 } },
  { name: 'Void Reaper', tagline: 'Eclipse crescent · bat wings', icon: 'moon', accent: '#a855f7',
    config: { element: 'void', itemType: 'scythe', headShape: 'crescent', gemColor: '#a855f7', gemColor2: '#ec4899', glowColor: '#7c3aed', shaftStyle: 'obsidian', shaftColor: '#1e1b2e', shaftColor2: '#0b0a14', wrapStyle: 'rune-band', wrapColor: '#a855f7', collarStyle: 'claw', collarColor: '#4c1d95', prongs: 2, wings: 'bat', wingColor: '#2e1065', halo: 'eclipse', haloColor: '#c084fc', particles: 14, particleStyle: 'dots', outerGlow: 0.7, finish: 'metallic', pommelStyle: 'spike', tipStyle: 'floating-gem', motif: 'void', motifIntensity: 0.85 } },
  { name: 'Celestial Paladin', tagline: 'Radiant star · sunburst halo', icon: 'sun', accent: '#eab308',
    config: { element: 'light', itemType: 'scepter', headShape: 'star', gemColor: '#fde047', gemColor2: '#fffbeb', glowColor: '#facc15', shaftStyle: 'royal', shaftColor: '#f5f0e6', shaftColor2: '#a89f8d', wrapStyle: 'spiral', wrapColor: '#d4af37', collarStyle: 'crown', collarColor: '#ffd700', prongs: 0, halo: 'sunburst', haloColor: '#ffd700', wings: 'seraph', wingColor: '#fef9c3', particles: 12, particleStyle: 'plus', outerGlow: 0.75, finish: 'metallic', pommelStyle: 'gem', tipStyle: 'crown', motif: 'rays', motifIntensity: 0.9 } },
  { name: 'Stormcaller', tagline: 'Crackling prism · blade wings', icon: 'zap', accent: '#6366f1',
    config: { element: 'lightning', itemType: 'staff', headShape: 'prism', gemColor: '#6366f1', gemColor2: '#22d3ee', glowColor: '#818cf8', shaftStyle: 'twisted', shaftColor: '#334155', shaftColor2: '#0f172a', wrapStyle: 'none', wrapColor: '#818cf8', collarStyle: 'guard', collarColor: '#94a3b8', prongs: 4, wings: 'blade', wingColor: '#94a3b8', particles: 14, particleStyle: 'mixed', outerGlow: 0.65, finish: 'metallic', pommelStyle: 'cap', innerStyle: 'swirl', tipStyle: 'star', motif: 'bolt', motifIntensity: 0.85 } },
  { name: 'Bloodmoon Ritual', tagline: 'Watchful eye · thorned bone', icon: 'eye', accent: '#f43f5e',
    config: { element: 'blood', itemType: 'crosier', headShape: 'eye', gemColor: '#f43f5e', gemColor2: '#fbbf24', glowColor: '#e11d48', shaftStyle: 'bone', shaftColor: '#e8dcc0', shaftColor2: '#8a7d5c', wrapStyle: 'rings', wrapColor: '#991b1b', collarStyle: 'ring', collarColor: '#7f1d1d', prongs: 2, horns: true, hornColor: '#e8dcc0', particles: 9, particleStyle: 'embers', outerGlow: 0.6, finish: 'weathered', pommelStyle: 'spike', shaftCurve: 0.1, tipStyle: 'spike', motif: 'drip', motifIntensity: 0.75 } },
  { name: 'Tidal Oracle', tagline: 'Teardrop pearl · fae shimmer', icon: 'waves', accent: '#06b6d4',
    config: { element: 'water', itemType: 'staff', headShape: 'teardrop', gemColor: '#22d3ee', gemColor2: '#f0fdfa', glowColor: '#06b6d4', shaftStyle: 'twisted', shaftColor: '#164e63', shaftColor2: '#082f49', wrapStyle: 'spiral', wrapColor: '#5eead4', collarStyle: 'ring', collarColor: '#5eead4', prongs: 3, wings: 'fae', wingColor: '#99f6e4', particles: 12, particleStyle: 'bubbles', outerGlow: 0.55, finish: 'glossy', pommelStyle: 'ring', innerStyle: 'swirl', tipStyle: 'floating-gem', motif: 'wave', motifIntensity: 0.7 } },
  { name: 'Gilded Emperor', tagline: 'Rune cube · opulent gold', icon: 'gem', accent: '#d4af37',
    config: { element: 'arcane', itemType: 'scepter', headShape: 'rune-cube', gemColor: '#ffd700', gemColor2: '#fff7cc', glowColor: '#eab308', shaftStyle: 'royal', shaftColor: '#3b1f0e', shaftColor2: '#1c0e05', wrapStyle: 'rune-band', wrapColor: '#ffd700', collarStyle: 'filigree', collarColor: '#ffd700', prongs: 4, halo: 'ring', haloColor: '#ffd700', particles: 10, particleStyle: 'diamonds', outerGlow: 0.5, finish: 'metallic', pommelStyle: 'gem', tipStyle: 'crown', motif: 'rune', motifIntensity: 0.45 } },
  { name: 'Witchwood Hex', tagline: 'Crystal cluster · violet mist', icon: 'sparkles', accent: '#8b5cf6',
    config: { element: 'arcane', itemType: 'cane', headShape: 'cluster', gemColor: '#8b5cf6', gemColor2: '#f0abfc', glowColor: '#8b5cf6', shaftStyle: 'gnarled', shaftColor: '#3f2d1e', shaftColor2: '#171008', wrapStyle: 'vine', wrapColor: '#7c3aed', collarStyle: 'claw', collarColor: '#5b21b6', prongs: 2, particles: 15, particleStyle: 'sparkle', outerGlow: 0.7, finish: 'enchanted', pommelStyle: 'cap', innerStyle: 'galaxy', tipStyle: 'cluster', motif: 'rune', motifIntensity: 0.6 } },
  { name: 'Ivory Requiem', tagline: 'Crystal skull · requiem halo', icon: 'skull', accent: '#e8dcc0',
    config: { element: 'dark', itemType: 'scythe', headShape: 'skull', gemColor: '#e8e4d8', gemColor2: '#7c3aed', glowColor: '#a78bfa', shaftStyle: 'bone', shaftColor: '#ddd3b8', shaftColor2: '#7a6f52', wrapStyle: 'chain', wrapColor: '#57534e', collarStyle: 'guard', collarColor: '#a8a29e', prongs: 0, halo: 'ring', haloColor: '#e7e5e4', particles: 7, particleStyle: 'dots', outerGlow: 0.45, finish: 'matte', pommelStyle: 'ring', tipStyle: 'floating-gem', motif: 'wisp', motifIntensity: 0.5 } },
  /* ── Mod-inspired Legend Presets ── */
  { name: 'Vis Primordial Staff', tagline: 'Thaumcraft · Greatwood Vis core & brass caps', icon: 'zap', accent: '#9333ea',
    config: { modEssence: 'thaumcraft', element: 'arcane', itemType: 'staff', headShape: 'orb', gemColor: '#9333ea', gemColor2: '#c084fc', glowColor: '#a855f7', shaftStyle: 'twisted', shaftColor: '#3b1d28', shaftColor2: '#1a0b12', wrapStyle: 'rune-band', wrapColor: '#d4af37', collarStyle: 'claw', collarColor: '#d4af37', prongs: 3, halo: 'rune-ring', haloColor: '#c084fc', tipStyle: 'gem', motif: 'rune', motifIntensity: 0.85, finish: 'enchanted', particles: 12, particleStyle: 'sparkle' } },
  { name: 'Rod of the Highlands', tagline: 'Botania · Dreamwood Mana crystal & living flora', icon: 'leaf', accent: '#22d3ee',
    config: { modEssence: 'botania', element: 'nature', itemType: 'rod', headShape: 'bloom', gemColor: '#22d3ee', gemColor2: '#4ade80', glowColor: '#06b6d4', shaftStyle: 'straight', shaftColor: '#f1f5f9', shaftColor2: '#94a3b8', wrapStyle: 'vine', wrapColor: '#4ade80', collarStyle: 'ring', collarColor: '#5eead4', prongs: 0, tipStyle: 'cluster', motif: 'mana-weave', motifIntensity: 0.9, finish: 'glossy', particles: 14, particleStyle: 'leaf' } },
  { name: 'Gravitite Sky-Scepter', tagline: 'The Aether · Floating gravitite & golden amber', icon: 'orbit', accent: '#38bdf8',
    config: { modEssence: 'aether', element: 'light', itemType: 'scepter', headShape: 'diamond', gemColor: '#f59e0b', gemColor2: '#fbbf24', glowColor: '#38bdf8', shaftStyle: 'ivory', shaftColor: '#cbd5e1', shaftColor2: '#475569', wrapStyle: 'spiral', wrapColor: '#fbbf24', collarStyle: 'crown', collarColor: '#e2e8f0', prongs: 2, halo: 'double', haloColor: '#bae6fd', tipStyle: 'floating-gem', orbiterStyle: 'shard', orbiterCount: 3, motif: 'rays', motifIntensity: 0.7, finish: 'metallic' } },
  { name: 'Hyperion Catalyst', tagline: 'Hypixel SkyBlock · Saturated wither blade essence', icon: 'flame', accent: '#f43f5e',
    config: { modEssence: 'hypixel-legend', element: 'fire', itemType: 'staff', headShape: 'crystal', gemColor: '#f43f5e', gemColor2: '#fbbf24', glowColor: '#e11d48', shaftStyle: 'obsidian', shaftColor: '#18181b', shaftColor2: '#09090b', wrapStyle: 'chain', wrapColor: '#fbbf24', collarStyle: 'guard', collarColor: '#e4e4e7', prongs: 4, tipStyle: 'crystal-tip', motif: 'flame', motifIntensity: 1, finish: 'glossy', outline: 'selout', contrast: 1.25, particles: 18, particleStyle: 'embers' } },
  { name: 'Astral Resonator', tagline: 'Astral Sorcery · Constellation starlight & navy marble', icon: 'star', accent: '#60a5fa',
    config: { modEssence: 'astral-sorcery', element: 'arcane', itemType: 'wand', headShape: 'star', gemColor: '#60a5fa', gemColor2: '#e0e7ff', glowColor: '#93c5fd', shaftStyle: 'royal', shaftColor: '#1e1b4b', shaftColor2: '#0f172a', wrapStyle: 'rings', wrapColor: '#f8fafc', collarStyle: 'filigree', collarColor: '#93c5fd', prongs: 2, halo: 'sunburst', haloColor: '#bfdbfe', tipStyle: 'star', motif: 'constellation', motifIntensity: 0.95, finish: 'metallic', particles: 16, particleStyle: 'diamonds' } },
  { name: 'Echo Ward of the Deep', tagline: 'Deep Dark · Sculk tendrils & resonant echo shard', icon: 'eye', accent: '#06b6d4',
    config: { modEssence: 'sculk-ancient', element: 'void', itemType: 'scythe', headShape: 'eye', gemColor: '#06b6d4', gemColor2: '#14b8a6', glowColor: '#0891b2', shaftStyle: 'bone', shaftColor: '#041e24', shaftColor2: '#020b0e', wrapStyle: 'rune-band', wrapColor: '#06b6d4', collarStyle: 'claw', collarColor: '#083344', prongs: 2, halo: 'eclipse', haloColor: '#155e75', tipStyle: 'floating-gem', motif: 'sculk-tendril', motifIntensity: 1, finish: 'weathered', particles: 12, particleStyle: 'dots' } },
  { name: 'Sakura Nekomata', tagline: '桜 · 薄紅舞う夜桜の杖 · jewels like falling petals', icon: 'leaf', accent: '#f9a8d4',
    config: { element: 'sakura', itemType: 'staff', headShape: 'lotus', gemColor: '#f9a8d4', gemColor2: '#fbcfe8', glowColor: '#f472b6', shaftStyle: 'gnarled', shaftColor: '#783c50', shaftColor2: '#4c1d2c', wrapStyle: 'vine', wrapColor: '#fecdd3', collarStyle: 'filigree', collarColor: '#cda0b5', prongs: 0, tipStyle: 'living-bloom', motif: 'petals', motifIntensity: 0.85, finish: 'glossy', particles: 16, particleStyle: 'leaf', wings: 'none', halo: 'none', outerGlow: 0.55, adornmentStyle: 'petal-mantle', adornmentDensity: 0.62 } },
  { name: 'Forgemaster Errand', tagline: '鋼 · 鍛錬者の遺業 · anvil-adorned steel mace', icon: 'hammer', accent: '#f59e0b',
    config: { element: 'steel', itemType: 'mace', headShape: 'anvil', gemColor: '#94a3b8', gemColor2: '#fcd34d', glowColor: '#d97706', shaftStyle: 'alloy', shaftColor: '#57534e', shaftColor2: '#26221f', wrapStyle: 'scale', wrapColor: '#b08968', collarStyle: 'guard', collarColor: '#e8c874', prongs: 0, tipStyle: 'blade', motif: 'gears', motifIntensity: 0.78, finish: 'metallic', particles: 12, particleStyle: 'firefly', adornmentStyle: 'gold-pave', adornmentDensity: 0.55, wearStyle: 'scratched', wearAmount: 0.25 } },
  { name: 'Cosmos Arcana Crown', tagline: '宇宙 · 星座の巡環 · aurora-crowned portal focus', icon: 'orbit', accent: '#818cf8',
    config: { element: 'cosmos', itemType: 'focus-orb', headShape: 'portal', gemColor: '#6366f1', gemColor2: '#a5b4fc', glowColor: '#818cf8', shaftStyle: 'obsidian', shaftColor: '#1e1b4b', shaftColor2: '#0d0a26', wrapStyle: 'rune-band', wrapColor: '#93c5fd', collarStyle: 'orb-cage', collarColor: '#60a5fa', prongs: 4, tipStyle: 'prism-trio', orbiterStyle: 'comet-dust', orbiterCount: 3, motif: 'constellation', motifIntensity: 1, halo: 'hex-grid', haloColor: '#93c5fd', finish: 'holographic', particles: 20, particleStyle: 'stars', outerGlow: 0.85 } },
  { name: 'Dunes Mirror One', tagline: '砂 · 砂嵐の先見 · meteor-bearing desert wand', icon: 'mountain', accent: '#f59e0b',
    config: { element: 'desert', itemType: 'wand', headShape: 'meteor', gemColor: '#f59e0b', gemColor2: '#fde68a', glowColor: '#fbbf24', shaftStyle: 'driftwood', shaftColor: '#7c5a35', shaftColor2: '#4a3721', wrapStyle: 'none', wrapColor: '#fbbf24', collarStyle: 'ring', collarColor: '#b08968', prongs: 2, tipStyle: 'gem-cluster', motif: 'rock', motifIntensity: 0.7, halo: 'sunburst', haloColor: '#fde68a', finish: 'weathered', particles: 11, particleStyle: 'glow-dust', dangleStyle: 'feather', dangleCount: 2 } },
  { name: 'Dragon Throne Bone', tagline: '竜 · 牙をあおぐ鎌 · dragon-fang scythe of ancient flame', icon: 'crown', accent: '#dc2626',
    config: { element: 'dragon', itemType: 'scythe', headShape: 'skull', gemColor: '#ef4444', gemColor2: '#fca5a5', glowColor: '#dc2626', shaftStyle: 'bone', shaftColor: '#44403c', shaftColor2: '#1c1917', wrapStyle: 'chain', wrapColor: '#7d7461', collarStyle: 'skull-collar', collarColor: '#e8dcc0', prongs: 0, tipStyle: 'dragon-fang', horns: true, hornColor: '#e8dcc0', motif: 'flame', motifIntensity: 0.9, finish: 'lacquered', particles: 14, particleStyle: 'embers', wings: 'none' } },
  { name: 'Psyche Moth Eye', tagline: '霊 · 幻惑の眼・蝶のしたたり · psyche eye staff', icon: 'moon', accent: '#c4b5fd',
    config: { element: 'psyche', itemType: 'staff', headShape: 'eye', gemColor: '#a78bfa', gemColor2: '#67e8f9', glowColor: '#c4b5fd', shaftStyle: 'crystal', shaftColor: '#312e81', shaftColor2: '#161342', wrapStyle: 'none', wrapColor: '#5eead4', collarStyle: 'filigree', collarColor: '#5eead4', prongs: 2, tipStyle: 'butterfly-tip', orbiterStyle: 'butterfly-swarm', orbiterCount: 4, motif: 'wisp', motifIntensity: 0.85, halo: 'spiral', haloColor: '#99f6e4', finish: 'frosted', particles: 15, particleStyle: 'firefly', outerGlow: 0.7 } },
  { name: 'Winter Bell Pineshower', tagline: '氷 · 雪灯籠の祝祭 · snow-globe censer', icon: 'snowflake', accent: '#b3e5fc',
    config: { element: 'ice', itemType: 'censer', headShape: 'snow-globe', gemColor: '#b3e5fc', gemColor2: '#e1f5fe', glowColor: '#81d4fa', shaftStyle: 'ivory', shaftColor: '#d7e4f0', shaftColor2: '#8faebc', wrapStyle: 'rings', wrapColor: '#38bdf8', collarStyle: 'bell-dome', collarColor: '#5eead4', prongs: 0, tipStyle: 'snow-globe-tip', dangleStyle: 'chain-charm', dangleCount: 3, motif: 'frost', motifIntensity: 0.85, finish: 'glossy', particles: 14, particleStyle: 'snow', halo: 'ring', haloColor: '#bae6fd' } },
  { name: 'Fortissimo Orgel Choir', tagline: '音 · 奏でる共鳴箱 · royal music-box crosier', icon: 'sun', accent: '#fcd34d',
    config: { element: 'sound', itemType: 'crosier', headShape: 'music-box', gemColor: '#fcd34d', gemColor2: '#fff1b8', glowColor: '#eab308', shaftStyle: 'royal', shaftColor: '#6e4a3f', shaftColor2: '#2c1d16', wrapStyle: 'spiral', wrapColor: '#e8c874', collarStyle: 'filigree', collarColor: '#ffd166', prongs: 0, tipStyle: 'prism-trio', orbiterStyle: 'rune', orbiterCount: 3, motif: 'music-notes', motifIntensity: 0.8, halo: 'triple', haloColor: '#ffd166', finish: 'glossy', particles: 14, particleStyle: 'plus', adornmentStyle: 'rune-engraving', adornmentDensity: 0.5 } },
];

export const STYLE_DNA = [
  { title: '光源は左上 45°', en: 'Light from top-left', desc: 'Minecraft アイテムテクスチャの標準。ハイライトは左上、影は右下へ。' },
  { title: '選択的アウトライン', en: 'Selective outline (sel-out)', desc: '輪郭線の色を隣接色から導出。光る側は明るく、影側は暗く。' },
  { title: '円筒のバンド', en: 'H → B → S → C → R', desc: 'ハイライト・基調・影・核心影・反射光の5段階で立体感を出す。' },
  { title: '狭いハイライト', en: 'Narrow highlights', desc: '金属は 5〜10% の面積のみ。広いとプラスチックに見える。' },
  { title: '彩度の高い差し色', en: 'Saturated accent', desc: 'Hypixel Skyblock 流。GUI 内で一目で読める鮮やかな主色。' },
  { title: '余白を残す', en: 'Leave breathing room', desc: 'アイコンは枠いっぱいに描かず、周囲に空間を残して読みやすく。' },
];
