import JSZip from "jszip";
import { exportToBlockbench } from "@/lib/exporters/blockbench";
import { exportBedrockAnimations, exportToMinecraftBedrock } from "@/lib/exporters/minecraftBedrock";
import { exportToMinecraftJava } from "@/lib/exporters/minecraftJava";
import { generateProceduralAtlas } from "@/lib/generators/textureBaker";
import { buildVariant, buildVariantSet, stripVariantName } from "@/lib/variants/variantEngine";
import { ModelCategory, ModelData, VariantState } from "@/types/model";

const NAMESPACE = "mcforge";

const BASE_ITEMS: Record<ModelCategory, string> = {
  sword: "diamond_sword",
  staff: "blaze_rod",
  magic: "book",
  armor: "netherite_chestplate",
  relic: "nether_star",
  ranged: "carrot_on_a_stick",
  custom: "stick",
};

function slugify(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9_]+/g, "_").replace(/^_+|_+$/g, "") || "model";
}

function dataUrlToBase64(dataUrl: string): string {
  return dataUrl.slice(dataUrl.indexOf(",") + 1);
}

export interface VariantPackResult {
  blob: Blob;
  fileName: string;
  variantCount: number;
}

export async function exportVariantPack(base: ModelData, current: VariantState): Promise<VariantPackResult> {
  const zip = new JSZip();
  const baseSlug = slugify(stripVariantName(base.name));
  const baseItem = BASE_ITEMS[base.category] ?? "stick";
  const entries = buildVariantSet(current);
  const readme: string[] = [
    `${stripVariantName(base.name)} — Variant Pack`,
    "Generated by Minecraft 3D Model Forge",
    "",
    `Base item: minecraft:${baseItem}`,
    "",
    "custom_model_data mapping:",
  ];

  const legacyOverrides: Array<{ predicate: { custom_model_data: number }; model: string }> = [];
  const dispatchEntries: Array<{ threshold: number; model: { type: string; model: string } }> = [];

  entries.forEach((entry, index) => {
    const cmd = index + 1;
    const variantModel = buildVariant(base, entry.state);
    const slug = `${baseSlug}_${entry.key}`;
    const texture = generateProceduralAtlas(variantModel.palette, base.textureWidth, entry.state);
    const modelRef = `${NAMESPACE}:item/${slug}`;

    zip.file(`resourcepack/assets/${NAMESPACE}/models/item/${slug}.json`, exportToMinecraftJava(variantModel, modelRef));
    zip.file(`resourcepack/assets/${NAMESPACE}/textures/item/${slug}.png`, dataUrlToBase64(texture), { base64: true });
    zip.file(`blockbench/${slug}.bbmodel`, exportToBlockbench(variantModel, texture));
    zip.file(`bedrock/models/entity/${slug}.geo.json`, exportToMinecraftBedrock(variantModel));
    zip.file(`bedrock/animations/${slug}.animation.json`, exportBedrockAnimations(variantModel));
    zip.file(`bedrock/textures/entity/${slug}.png`, dataUrlToBase64(texture), { base64: true });

    legacyOverrides.push({ predicate: { custom_model_data: cmd }, model: modelRef });
    dispatchEntries.push({ threshold: cmd, model: { type: "minecraft:model", model: modelRef } });
    readme.push(`  ${String(cmd).padStart(2, " ")} → ${variantModel.name}  (${slug})`);
  });

  // Legacy (≤1.21.3) item model overrides
  zip.file(
    `resourcepack/assets/minecraft/models/item/${baseItem}.json`,
    JSON.stringify(
      {
        parent: "minecraft:item/handheld",
        textures: { layer0: `minecraft:item/${baseItem}` },
        overrides: legacyOverrides,
      },
      null,
      2,
    ),
  );

  // 1.21.4+ item model definition
  zip.file(
    `resourcepack/assets/minecraft/items/${baseItem}.json`,
    JSON.stringify(
      {
        model: {
          type: "minecraft:range_dispatch",
          property: "minecraft:custom_model_data",
          index: 0,
          fallback: { type: "minecraft:model", model: `minecraft:item/${baseItem}` },
          entries: dispatchEntries,
        },
      },
      null,
      2,
    ),
  );

  zip.file(
    "resourcepack/pack.mcmeta",
    JSON.stringify(
      {
        pack: {
          pack_format: 46,
          supported_formats: { min_inclusive: 15, max_inclusive: 99 },
          description: `${stripVariantName(base.name)} variants (${entries.length})`,
        },
      },
      null,
      2,
    ),
  );

  readme.push(
    "",
    "Commands:",
    `  1.21.4+ : /give @p minecraft:${baseItem}[custom_model_data={floats:[N]}]`,
    `  1.20.5–1.21.3 : /give @p minecraft:${baseItem}[custom_model_data=N]`,
    `  ≤1.20.4 : /give @p minecraft:${baseItem}{CustomModelData:N}`,
    "",
    "Every .bbmodel and .animation.json contains: idle_float, attack_slash, attack_thrust,",
    "combo_strike, spell_charge, spell_release, ultimate_burst, transform.",
  );
  zip.file("README.txt", readme.join("\n"));

  const blob = await zip.generateAsync({ type: "blob", compression: "DEFLATE" });
  return { blob, fileName: `${baseSlug}_variant_pack.zip`, variantCount: entries.length };
}
