import type { AnimationConfig, StaffConfig } from './types';

export const DEFAULT_ANIMATION: AnimationConfig = {
  type: 'none', fps: 20, frames: 16, intensity: 0.8, loopMode: 'loop',
  mcmeta: true, blendGlint: false, frameByFrame: true,
};

export const DEFAULT_CONFIG: StaffConfig = {
  seed: 1337,
  resolution: 64,
  refined: true,
  animation: { ...DEFAULT_ANIMATION },
  modEssence: 'none',
  gemCut: 'brilliant',
  gemMount: 'claw',
  gemCount: 3,
  gemScale: 0.18,
  adornmentStyle: 'filigree',
  adornmentDensity: 0.45,
  rarity: 'epic',
  harmony: 'custom',
  paletteSize: 0,
  softEdge: false,
  dangleStyle: 'none',
  dangleCount: 2,
  wearStyle: 'none',
  wearAmount: 0.35,
  motif2: 'none',
  motif2Intensity: 0.4,
  element: 'arcane',
  itemType: 'staff',
  shaftLength: 0.86,
  shaftThickness: 0.062,
  shaftAngle: -48,
  shaftCurve: 0.04,
  shaftStyle: 'royal',
  shaftColor: '#6b4226',
  shaftColor2: '#3d2413',
  shaftDetail: 0.45,
  wrapStyle: 'spiral',
  wrapColor: '#d4af37',
  wrapDensity: 6,
  collarStyle: 'filigree',
  collarColor: '#d4af37',
  headShape: 'orb',
  headSize: 0.3,
  gemColor: '#7c3aed',
  gemColor2: '#22d3ee',
  gemGlow: 0.8,
  innerStyle: 'galaxy',
  prongs: 3,
  prongColor: '#e8c874',
  tipStyle: 'gem',
  tipScale: 0.5,
  orbiterStyle: 'none',
  orbiterCount: 3,
  orbiterRadius: 1.55,
  orbiterSize: 0.14,
  pommelStyle: 'gem',
  pommelColor: '#d4af37',
  wings: 'none',
  wingColor: '#f5f0e6',
  halo: 'none',
  haloColor: '#ffd700',
  horns: false,
  hornColor: '#e8dcc0',
  particles: 10,
  particleStyle: 'sparkle',
  particleColor: '#c4b5fd',
  outline: 'selout',
  shading: 0.75,
  dither: true,
  outerGlow: 0.28,
  glowColor: '#7c3aed',
  dropShadow: false,
  finish: 'enchanted',
  contrast: 1.1,
  grain: 0.35,
  motif: 'rune',
  motifIntensity: 0.5,
};
