/** Static Minecraft/editor catalog values. */
export interface NamedConst {
  key: string; // Kotlin constant name
  label: string;
}

export const EFFECTS: NamedConst[] = [
  { key: "SPEED", label: "移動速度上昇" },
  { key: "SLOWNESS", label: "移動速度低下" },
  { key: "HASTE", label: "採掘速度上昇" },
  { key: "MINING_FATIGUE", label: "採掘速度低下" },
  { key: "STRENGTH", label: "攻撃力上昇" },
  { key: "INSTANT_HEALTH", label: "即時回復" },
  { key: "INSTANT_DAMAGE", label: "即時ダメージ" },
  { key: "JUMP_BOOST", label: "跳躍力上昇" },
  { key: "NAUSEA", label: "吐き気" },
  { key: "REGENERATION", label: "再生能力" },
  { key: "RESISTANCE", label: "耐性" },
  { key: "FIRE_RESISTANCE", label: "火炎耐性" },
  { key: "WATER_BREATHING", label: "水中呼吸" },
  { key: "INVISIBILITY", label: "透明化" },
  { key: "BLINDNESS", label: "盲目" },
  { key: "NIGHT_VISION", label: "暗視" },
  { key: "HUNGER", label: "空腹" },
  { key: "WEAKNESS", label: "弱体化" },
  { key: "POISON", label: "毒" },
  { key: "WITHER", label: "衰弱(ウィザー)" },
  { key: "ABSORPTION", label: "ダメージ吸収" },
  { key: "GLOWING", label: "発光" },
  { key: "LEVITATION", label: "浮遊" },
  { key: "SLOW_FALLING", label: "低速落下" },
  { key: "DARKNESS", label: "暗闇" },
  { key: "BAD_OMEN", label: "不吉な予感" },
  { key: "RAID_OMEN", label: "襲撃の予感" },
  { key: "TRIAL_OMEN", label: "試練の予感" },
  { key: "HERO_OF_THE_VILLAGE", label: "村の英雄" },
  { key: "DOLPHINS_GRACE", label: "イルカの好意" },
  { key: "LUCK", label: "幸運" },
  { key: "UNLUCK", label: "不運" },
  { key: "CONDUIT_POWER", label: "コンジットのパワー" },
  { key: "SATURATION", label: "満腹度回復" },
  { key: "WIND_CHARGED", label: "風纏い (1.21)" },
  { key: "WEAVING", label: "織り込み (1.21)" },
  { key: "OOZING", label: "滲出 (1.21)" },
  { key: "INFESTED", label: "寄生 (1.21)" },
];

export const PARTICLES: NamedConst[] = [
  { key: "FLAME", label: "炎" },
  { key: "SMOKE", label: "煙" },
  { key: "HEART", label: "ハート" },
  { key: "CRIT", label: "クリティカル" },
  { key: "ENCHANT", label: "エンチャント" },
  { key: "EXPLOSION", label: "爆発" },
  { key: "END_ROD", label: "エンドロッド" },
  { key: "SOUL_FIRE_FLAME", label: "魂の炎" },
  { key: "SNOWFLAKE", label: "雪の結晶" },
  { key: "CLOUD", label: "雲" },
  { key: "WITCH", label: "魔女" },
  { key: "HAPPY_VILLAGER", label: "緑のキラキラ" },
  { key: "LAVA", label: "溶岩" },
  { key: "DRAGON_BREATH", label: "ドラゴンブレス" },
  { key: "TOTEM_OF_UNDYING", label: "不死のトーテム" },
  { key: "ELECTRIC_SPARK", label: "電気火花" },
  { key: "SWEEP_ATTACK", label: "薙ぎ払い" },
  { key: "PORTAL", label: "ポータル" },
  { key: "NOTE", label: "音符" },
  { key: "ANGRY_VILLAGER", label: "怒りの村人マーク" },
  { key: "BUBBLE", label: "水泡" },
  { key: "BUBBLE_POP", label: "水泡(はじける)" },
  { key: "CHERRY_LEAVES", label: "桜の花びら" },
  { key: "FLASH", label: "閃光(瞬時)" },
  { key: "SNEEZE", label: "くしゃみ" },
  { key: "SPIT", label: "唾" },
  { key: "COMPOSTER", label: "コンポスター" },
  { key: "ASH", label: "灰" },
  { key: "WHITE_ASH", label: "白い灰" },
  { key: "SCRAPE", label: "スクレイプ(銅)" },
  { key: "WAX_OFF", label: "ワックス剥がれ" },
  { key: "GLOW", label: "グロウ(発光)" },
  { key: "GLOW_SQUID_INK", label: "グロウイカの墨" },
  { key: "REVERSE_PORTAL", label: "逆ポータル" },
  { key: "FALLING_LAVA", label: "落ちる溶岩" },
  { key: "FALLING_WATER", label: "落ちる水" },
  { key: "ITEM_SLIME", label: "スライム(アイテム)" },
  { key: "ITEM_SNOWBALL", label: "雪玉(アイテム)" },
];

export const SOUNDS: NamedConst[] = [
  { key: "ENTITY_PLAYER_LEVELUP", label: "レベルアップ" },
  { key: "ENTITY_GENERIC_EXPLODE", label: "爆発音" },
  { key: "ENTITY_LIGHTNING_BOLT_THUNDER", label: "雷鳴" },
  { key: "ENTITY_ENDERMAN_TELEPORT", label: "テレポート" },
  { key: "ENTITY_BLAZE_SHOOT", label: "ブレイズ発射" },
  { key: "ENTITY_EXPERIENCE_ORB_PICKUP", label: "経験値取得" },
  { key: "ENTITY_PLAYER_ATTACK_SWEEP", label: "薙ぎ払い" },
  { key: "ENTITY_WITHER_SHOOT", label: "ウィザー発射" },
  { key: "BLOCK_ANVIL_LAND", label: "金床着地" },
  { key: "ENTITY_ENDER_DRAGON_GROWL", label: "ドラゴンの咆哮" },
  { key: "ENTITY_FIREWORK_ROCKET_LAUNCH", label: "花火打ち上げ" },
  { key: "BLOCK_BEACON_ACTIVATE", label: "ビーコン起動" },
  { key: "ENTITY_ILLUSIONER_CAST_SPELL", label: "呪文詠唱" },
  { key: "ITEM_FIRECHARGE_USE", label: "ファイアチャージ" },
  { key: "ENTITY_ARROW_SHOOT", label: "弓発射" },
  { key: "ENTITY_ARROW_HIT", label: "矢命中" },
  { key: "ENTITY_GENERIC_DRINK", label: "飲む音" },
  { key: "ENTITY_GENERIC_EAT", label: "食べる音" },
  { key: "ENTITY_GENERIC_BURN", label: "燃える音" },
  { key: "ENTITY_GENERIC_EXTINGUISH_FIRE", label: "消火音" },
  { key: "ENTITY_PLAYER_BURP", label: "げっぷ" },
  { key: "ENTITY_PLAYER_HURT", label: "プレイヤー被弾" },
  { key: "ENTITY_ITEM_BREAK", label: "アイテム破損" },
  { key: "ENTITY_VILLAGER_YES", label: "村人(肯定)" },
  { key: "ENTITY_VILLAGER_NO", label: "村人(否定)" },
  { key: "ENTITY_ZOMBIE_AMBIENT", label: "ゾンビの声" },
  { key: "ENTITY_WITHER_SPAWN", label: "ウィザー出現" },
  { key: "ITEM_TRIDENT_THROW", label: "トライデント投擲" },
  { key: "ITEM_TRIDENT_THUNDER", label: "トライデント雷" },
  { key: "BLOCK_NOTE_BLOCK_PLING", label: "音符ブロック(プリング)" },
  { key: "BLOCK_NOTE_BLOCK_HARP", label: "音符ブロック(ハープ)" },
  { key: "BLOCK_GLASS_BREAK", label: "ガラス破壊" },
  { key: "BLOCK_AMETHYST_BLOCK_CHIME", label: "アメジストの音色" },
  { key: "BLOCK_BELL_USE", label: "鐘" },
  { key: "BLOCK_PORTAL_TRAVEL", label: "ポータル移動" },
];

export const BLOCK_SOUNDS = [
  "STONE", "WOOD", "METAL", "GLASS", "GRAVEL", "GRASS", "SAND", "WOOL", "AMETHYST_BLOCK",
  "NETHERITE_BLOCK", "COPPER", "DEEPSLATE", "TUFF", "CALCITE", "DRIPSTONE_BLOCK", "BONE_BLOCK",
  "SLIME", "HONEY", "LANTERN", "CHAIN", "ROOTED_DIRT", "MOSS",
];

export const ITEM_TEXTURES = [
  "minecraft:item/nether_star",
  "minecraft:item/blaze_rod",
  "minecraft:item/stick",
  "minecraft:item/diamond",
  "minecraft:item/emerald",
  "minecraft:item/iron_ingot",
  "minecraft:item/gold_ingot",
  "minecraft:item/amethyst_shard",
  "minecraft:item/fire_charge",
  "minecraft:item/ender_pearl",
  "minecraft:item/book",
  "minecraft:item/diamond_sword",
  "minecraft:item/iron_sword",
  "minecraft:item/golden_apple",
  "minecraft:item/bread",
  "minecraft:item/echo_shard",
  "minecraft:item/heart_of_the_sea",
  "minecraft:item/wooden_sword",
  "minecraft:item/stone_sword",
  "minecraft:item/golden_sword",
  "minecraft:item/netherite_sword",
  "minecraft:item/diamond_pickaxe",
  "minecraft:item/iron_pickaxe",
  "minecraft:item/netherite_pickaxe",
  "minecraft:item/diamond_axe",
  "minecraft:item/bow",
  "minecraft:item/trident",
  "minecraft:item/shield",
  "minecraft:item/totem_of_undying",
  "minecraft:item/netherite_ingot",
  "minecraft:item/copper_ingot",
  "minecraft:item/glow_berries",
  "minecraft:item/sweet_berries",
  "minecraft:item/ender_eye",
  "minecraft:item/prismarine_crystals",
  "minecraft:item/phantom_membrane",
  "minecraft:item/rabbit_foot",
  "minecraft:item/honey_bottle",
  "minecraft:item/cooked_beef",
  "minecraft:item/enchanted_golden_apple",
  "minecraft:item/experience_bottle",
  "minecraft:item/name_tag",
  "minecraft:item/diamond_helmet",
  "minecraft:item/diamond_chestplate",
  "minecraft:item/iron_chestplate",
  "minecraft:item/leather_helmet",
];

export const BLOCK_TEXTURES = [
  "minecraft:block/stone",
  "minecraft:block/obsidian",
  "minecraft:block/diamond_block",
  "minecraft:block/gold_block",
  "minecraft:block/iron_block",
  "minecraft:block/emerald_block",
  "minecraft:block/amethyst_block",
  "minecraft:block/glowstone",
  "minecraft:block/magma",
  "minecraft:block/oak_planks",
  "minecraft:block/sea_lantern",
  "minecraft:block/crying_obsidian",
  "minecraft:block/redstone_block",
  "minecraft:block/iron_ore",
  "minecraft:block/deepslate_iron_ore",
  "minecraft:block/deepslate_diamond_ore",
  "minecraft:block/nether_gold_ore",
  "minecraft:block/ancient_debris_side",
  "minecraft:block/soul_soil",
  "minecraft:block/netherrack",
  "minecraft:block/end_stone",
  "minecraft:block/moss_block",
  "minecraft:block/sculk",
  "minecraft:block/copper_block",
  "minecraft:block/netherite_block",
  "minecraft:block/quartz_block_side",
  "minecraft:block/prismarine",
  "minecraft:block/purpur_block",
  "minecraft:block/bookshelf",
  "minecraft:block/smithing_table_front",
  "minecraft:block/barrel_top",
  "minecraft:block/beacon",
  "minecraft:block/dragon_egg",
  "minecraft:block/emerald_ore",
];

export const ENTITY_TYPES: NamedConst[] = [
  { key: "ZOMBIE", label: "ゾンビ" },
  { key: "SKELETON", label: "スケルトン" },
  { key: "CREEPER", label: "クリーパー" },
  { key: "SPIDER", label: "クモ" },
  { key: "ENDERMAN", label: "エンダーマン" },
  { key: "BLAZE", label: "ブレイズ" },
  { key: "WITHER_SKELETON", label: "ウィザースケルトン" },
  { key: "VEX", label: "ヴェックス" },
  { key: "WOLF", label: "オオカミ" },
  { key: "IRON_GOLEM", label: "アイアンゴーレム" },
  { key: "SNOW_GOLEM", label: "スノーゴーレム" },
  { key: "ALLAY", label: "アレイ" },
  { key: "BEE", label: "ミツバチ" },
  { key: "VILLAGER", label: "村人" },
  { key: "MAGMA_CUBE", label: "マグマキューブ" },
  { key: "SLIME", label: "スライム" },
  { key: "GHAST", label: "ガスト" },
  { key: "DROWNED", label: "ドラウンド" },
  { key: "HUSK", label: "ハスク" },
  { key: "STRAY", label: "ストレイ" },
  { key: "PILLAGER", label: "ピリジャー" },
  { key: "VINDICATOR", label: "ヴィンディケーター" },
  { key: "EVOKER", label: "エヴォーカー" },
  { key: "RAVAGER", label: "ラヴェジャー" },
  { key: "WITCH", label: "ウィッチ" },
  { key: "PHANTOM", label: "ファントム" },
  { key: "GUARDIAN", label: "ガーディアン" },
  { key: "ELDER_GUARDIAN", label: "エルダーガーディアン" },
  { key: "SHULKER", label: "シュルカー" },
  { key: "BREEZE", label: "ブリーズ (1.21)" },
  { key: "BOGGED", label: "ボグド (1.21)" },
  { key: "CAMEL", label: "ラクダ" },
  { key: "SNIFFER", label: "スニファー" },
  { key: "ARMADILLO", label: "アルマジロ (1.21)" },
  { key: "PIGLIN", label: "ピグリン" },
  { key: "PIGLIN_BRUTE", label: "ピグリンブルート" },
  { key: "HOGLIN", label: "ホグリン" },
  { key: "ZOGLIN", label: "ゾグリン" },
  { key: "STRIDER", label: "ストライダー" },
  { key: "CAT", label: "ネコ" },
  { key: "OCELOT", label: "ヤマネコ" },
  { key: "FOX", label: "キツネ" },
  { key: "PARROT", label: "オウム" },
  { key: "AXOLOTL", label: "ウーパールーパー" },
  { key: "GOAT", label: "ヤギ" },
  { key: "FROG", label: "カエル" },
  { key: "HORSE", label: "ウマ" },
  { key: "DONKEY", label: "ロバ" },
  { key: "PANDA", label: "パンダ" },
  { key: "POLAR_BEAR", label: "シロクマ" },
];

export const PLACE_BLOCKS: NamedConst[] = [
  { key: "FIRE", label: "火" },
  { key: "SOUL_FIRE", label: "ソウルファイア" },
  { key: "OBSIDIAN", label: "黒曜石" },
  { key: "COBWEB", label: "クモの巣" },
  { key: "MAGMA_BLOCK", label: "マグマブロック" },
  { key: "CAMPFIRE", label: "キャンプファイア" },
  { key: "POWDER_SNOW", label: "粉雪" },
  { key: "TNT", label: "TNT" },
  { key: "WATER", label: "水" },
  { key: "LAVA", label: "溶岩" },
  { key: "ICE", label: "氷" },
  { key: "GLOWSTONE", label: "グロウストーン" },
  { key: "CRYING_OBSIDIAN", label: "泣く黒曜石" },
  { key: "BARRIER", label: "バリア" },
  { key: "SPONGE", label: "スポンジ" },
  { key: "SLIME_BLOCK", label: "スライムブロック" },
  { key: "HONEY_BLOCK", label: "ハニーブロック" },
  { key: "SNOW_BLOCK", label: "雪ブロック" },
  { key: "BLUE_ICE", label: "青氷" },
  { key: "SAND", label: "砂" },
  { key: "GRAVEL", label: "砂利" },
  { key: "MOSS_BLOCK", label: "苔ブロック" },
  { key: "SCULK", label: "スカルク" },
  { key: "AMETHYST_BLOCK", label: "アメジストブロック" },
  { key: "SEA_LANTERN", label: "シーランタン" },
  { key: "SHROOMLIGHT", label: "シュルームライト" },
  { key: "RESPAWN_ANCHOR", label: "リスポーンアンカー" },
  { key: "LADDER", label: "はしご" },
];

export const COMMON_VANILLA_ITEMS = [
  "minecraft:stick", "minecraft:diamond", "minecraft:iron_ingot", "minecraft:gold_ingot", "minecraft:emerald",
  "minecraft:redstone", "minecraft:lapis_lazuli", "minecraft:coal", "minecraft:blaze_rod", "minecraft:blaze_powder",
  "minecraft:nether_star", "minecraft:ender_pearl", "minecraft:amethyst_shard", "minecraft:obsidian",
  "minecraft:cobblestone", "minecraft:oak_planks", "minecraft:glowstone_dust", "minecraft:book",
  "minecraft:paper", "minecraft:string", "minecraft:feather", "minecraft:gunpowder", "minecraft:apple",
  "minecraft:golden_apple", "minecraft:bread", "minecraft:diamond_block", "minecraft:iron_block",
  "minecraft:copper_ingot", "minecraft:netherite_ingot", "minecraft:netherite_scrap", "minecraft:quartz",
  "minecraft:glow_berries", "minecraft:sweet_berries", "minecraft:honey_bottle", "minecraft:totem_of_undying",
  "minecraft:ender_eye", "minecraft:prismarine_shard", "minecraft:prismarine_crystals", "minecraft:phantom_membrane",
  "minecraft:rabbit_foot", "minecraft:ghast_tear", "minecraft:magma_cream", "minecraft:slime_ball",
  "minecraft:bone", "minecraft:rotten_flesh", "minecraft:spider_eye", "minecraft:experience_bottle",
  "minecraft:name_tag", "minecraft:saddle", "minecraft:bow", "minecraft:arrow", "minecraft:shield",
  "minecraft:flint", "minecraft:flint_and_steel", "minecraft:bucket", "minecraft:snowball",
  "minecraft:clay_ball", "minecraft:brick", "minecraft:nether_brick", "minecraft:quartz_block",
  "minecraft:raw_iron", "minecraft:raw_gold", "minecraft:raw_copper", "minecraft:deepslate",
  "minecraft:tuff", "minecraft:calcite", "minecraft:dripstone_block", "minecraft:moss_block",
  "minecraft:bamboo", "minecraft:sugar_cane", "minecraft:cactus", "minecraft:pumpkin",
  "minecraft:carved_pumpkin", "minecraft:melon_slice", "minecraft:golden_carrot", "minecraft:carrot",
  "minecraft:potato", "minecraft:beetroot", "minecraft:egg", "minecraft:wheat", "minecraft:wheat_seeds",
  "minecraft:leather", "minecraft:rabbit_hide", "minecraft:turtle_scute", "minecraft:nautilus_shell",
];

/** 構造物生成でよく使うバイオームタグ */
export const BIOME_TAGS = [
  "#minecraft:is_overworld", "#minecraft:is_forest", "#minecraft:is_plains", "#minecraft:is_taiga",
  "#minecraft:is_mountain", "#minecraft:is_hill", "#minecraft:is_jungle", "#minecraft:is_savanna",
  "#minecraft:is_badlands", "#minecraft:is_desert", "#minecraft:is_swamp", "#minecraft:is_mushroom",
  "#minecraft:is_ocean", "#minecraft:is_river", "#minecraft:is_beach", "#minecraft:is_snowy",
  "#minecraft:is_icy", "#minecraft:is_cherry_grove", "#minecraft:is_pale_garden",
  "#minecraft:is_nether", "#minecraft:is_end",
  "minecraft:plains", "minecraft:forest", "minecraft:desert", "minecraft:snowy_plains",
];

/** 1.21.11 のエンチャント (公式マッピング Enchantments と照合済み) */
export const ENCHANTMENTS: NamedConst[] = [
  { key: "PROTECTION", label: "保護" },
  { key: "FIRE_PROTECTION", label: "火炎耐性" },
  { key: "FEATHER_FALLING", label: "落下耐性" },
  { key: "BLAST_PROTECTION", label: "爆発耐性" },
  { key: "PROJECTILE_PROTECTION", label: "飛び道具耐性" },
  { key: "RESPIRATION", label: "水中呼吸" },
  { key: "AQUA_AFFINITY", label: "水中採掘" },
  { key: "THORNS", label: "棘" },
  { key: "DEPTH_STRIDER", label: "水中歩行" },
  { key: "FROST_WALKER", label: "氷渡り" },
  { key: "BINDING_CURSE", label: "束縛の呪い" },
  { key: "SOUL_SPEED", label: "ソウルスピード" },
  { key: "SWIFT_SNEAK", label: "スニーク高速化" },
  { key: "SHARPNESS", label: "鋭さ" },
  { key: "SMITE", label: "聖なる力" },
  { key: "BANE_OF_ARTHROPODS", label: "虫殺し" },
  { key: "KNOCKBACK", label: "ノックバック" },
  { key: "FIRE_ASPECT", label: "火の属性" },
  { key: "LOOTING", label: "ドロップ増加" },
  { key: "SWEEPING_EDGE", label: "範囲ダメージ" },
  { key: "EFFICIENCY", label: "効率強化" },
  { key: "SILK_TOUCH", label: "シルクタッチ" },
  { key: "UNBREAKING", label: "耐久力" },
  { key: "FORTUNE", label: "幸運" },
  { key: "POWER", label: "射撃ダメージ増加" },
  { key: "PUNCH", label: "パンチ" },
  { key: "FLAME", label: "火の矢" },
  { key: "INFINITY", label: "無限" },
  { key: "LUCK_OF_THE_SEA", label: "宝釣り" },
  { key: "LURE", label: "入れ食い" },
  { key: "LOYALTY", label: "忠誠" },
  { key: "IMPALING", label: "水生特攻" },
  { key: "RIPTIDE", label: "激流" },
  { key: "CHANNELING", label: "召雷" },
  { key: "MULTISHOT", label: "拡散" },
  { key: "QUICK_CHARGE", label: "高速装填" },
  { key: "PIERCING", label: "貫通" },
  { key: "MENDING", label: "修繕" },
  { key: "VANISHING_CURSE", label: "消滅の呪い" },
  { key: "DENSITY", label: "密度 (1.21)" },
  { key: "BREACH", label: "突破 (1.21)" },
  { key: "WIND_BURST", label: "風襲 (1.21)" },
];

/** 1.21.11 の防具素材 (公式マッピング ArmorMaterials と照合済み) */
export const ARMOR_MATERIALS: NamedConst[] = [
  { key: "LEATHER", label: "革" },
  { key: "COPPER", label: "銅" },
  { key: "CHAINMAIL", label: "チェーン" },
  { key: "IRON", label: "鉄" },
  { key: "GOLD", label: "金" },
  { key: "DIAMOND", label: "ダイヤモンド" },
  { key: "TURTLE_SCUTE", label: "トータスカルート" },
  { key: "NETHERITE", label: "ネザライト" },
  { key: "ARMADILLO_SCUTE", label: "アルマジロの甲羅" },
];

/** 溶鉱炉など調理系レシピの種類 */
export const COOKING_RECIPE_TYPES = [
  { value: "smelting", label: "かまど (Smelting)", defaultTicks: 200, defaultXp: 0.1 },
  { value: "blasting", label: "溶鉱炉 (Blasting)", defaultTicks: 100, defaultXp: 0.1 },
  { value: "smoking", label: "燻製器 (Smoking)", defaultTicks: 100, defaultXp: 0.1 },
  { value: "campfire_cooking", label: "焚き火 (Campfire Cooking)", defaultTicks: 600, defaultXp: 0.1 },
] as const;
