import type { ElementDef, ElementType, StaffConfig } from '../types';

export const ELEMENTS: ElementDef[] = [
  { id: 'arcane', name: '秘術', nameEn: 'Arcane', icon: 'sparkles', gem: '#7c3aed', gem2: '#22d3ee', glow: '#8b5cf6', particle: '#c4b5fd', metal: '#d4af37', shaft: '#4a2c17', shaft2: '#241408', particleStyle: 'sparkle', head: 'orb', motif: 'rune', shaftStyle: 'royal', halo: 'rune-ring', tip: 'gem', wings: 'none', finish: 'enchanted', desc: '均衡した魔力 · ルーンと星' },
  { id: 'fire', name: '炎', nameEn: 'Inferno', icon: 'flame', gem: '#ff5722', gem2: '#ffd54f', glow: '#ff6b1a', particle: '#ffb347', metal: '#b87333', shaft: '#2b1a12', shaft2: '#120905', particleStyle: 'embers', head: 'crystal', motif: 'flame', shaftStyle: 'gnarled', halo: 'none', tip: 'flame', wings: 'none', finish: 'glossy', desc: '燃え盛る業火 · 火の粉' },
  { id: 'ice', name: '氷', nameEn: 'Glacier', icon: 'snowflake', gem: '#4fc3f7', gem2: '#e1f5fe', glow: '#29b6f6', particle: '#b3e5fc', metal: '#cfd8dc', shaft: '#dbeafe', shaft2: '#64748b', particleStyle: 'diamonds', head: 'diamond', motif: 'frost', shaftStyle: 'straight', halo: 'ring', tip: 'crystal-tip', wings: 'angel', finish: 'glossy', desc: '永久凍土 · 霜の結晶' },
  { id: 'lightning', name: '雷', nameEn: 'Tempest', icon: 'zap', gem: '#ffd54f', gem2: '#fffde7', glow: '#ffeb3b', particle: '#fff59d', metal: '#90a4ae', shaft: '#334155', shaft2: '#0f172a', particleStyle: 'mixed', head: 'prism', motif: 'bolt', shaftStyle: 'twisted', halo: 'double', tip: 'star', wings: 'blade', finish: 'metallic', desc: '稲妻の脈動 · 放電' },
  { id: 'nature', name: '自然', nameEn: 'Verdant', icon: 'leaf', gem: '#66bb6a', gem2: '#dcedc8', glow: '#4caf50', particle: '#a5d6a7', metal: '#8d6e63', shaft: '#4d3b28', shaft2: '#241a10', particleStyle: 'leaf', head: 'bloom', motif: 'leaf', shaftStyle: 'gnarled', halo: 'none', tip: 'cluster', wings: 'fae', finish: 'matte', desc: '生命の息吹 · 蔦と葉' },
  { id: 'light', name: '聖', nameEn: 'Radiant', icon: 'sun', gem: '#ffca28', gem2: '#fffde7', glow: '#ffc107', particle: '#fff9c4', metal: '#ffd700', shaft: '#f5f0e6', shaft2: '#a89f8d', particleStyle: 'plus', head: 'star', motif: 'rays', shaftStyle: 'royal', halo: 'sunburst', tip: 'crown', wings: 'seraph', finish: 'metallic', desc: '神聖なる光 · 太陽の冠' },
  { id: 'dark', name: '闇', nameEn: 'Umbral', icon: 'moon', gem: '#5e35b1', gem2: '#b39ddb', glow: '#7e57c2', particle: '#ce93d8', metal: '#5c6bc0', shaft: '#1e1b2e', shaft2: '#0b0a14', particleStyle: 'dots', head: 'crescent', motif: 'wisp', shaftStyle: 'twisted', halo: 'eclipse', tip: 'floating-gem', wings: 'bat', finish: 'metallic', desc: '影の抱擁 · 闇の霧' },
  { id: 'blood', name: '血', nameEn: 'Sanguine', icon: 'droplet', gem: '#c62828', gem2: '#ef9a9a', glow: '#e53935', particle: '#ff8a80', metal: '#8d6e63', shaft: '#e8dcc0', shaft2: '#8a7d5c', particleStyle: 'embers', head: 'eye', motif: 'drip', shaftStyle: 'bone', halo: 'none', tip: 'spike', wings: 'none', finish: 'weathered', desc: '赤い月の儀式 · 血の滴' },
  { id: 'water', name: '水', nameEn: 'Tidal', icon: 'waves', gem: '#0288d1', gem2: '#b3e5fc', glow: '#03a9f4', particle: '#80deea', metal: '#80deea', shaft: '#164e63', shaft2: '#082f49', particleStyle: 'bubbles', head: 'teardrop', motif: 'wave', shaftStyle: 'twisted', halo: 'ring', tip: 'floating-gem', wings: 'fae', finish: 'glossy', desc: '潮の律動 · 泡と波' },
  { id: 'earth', name: '地', nameEn: 'Titan', icon: 'mountain', gem: '#8d6e63', gem2: '#d7ccc8', glow: '#a1887f', particle: '#bcaaa4', metal: '#a1887f', shaft: '#5d4037', shaft2: '#3e2723', particleStyle: 'dots', head: 'rune-cube', motif: 'rock', shaftStyle: 'segmented', halo: 'none', tip: 'crown', wings: 'none', finish: 'weathered', desc: '大地の重み · 岩石' },
  { id: 'void', name: '虚空', nameEn: 'Void', icon: 'orbit', gem: '#311b92', gem2: '#7c4dff', glow: '#651fff', particle: '#b388ff', metal: '#b0bec5', shaft: '#1a1030', shaft2: '#08060f', particleStyle: 'dots', head: 'moonlet', motif: 'void', shaftStyle: 'obsidian', halo: 'eclipse', tip: 'floating-gem', wings: 'bat', finish: 'matte', desc: '無の中心 · 星食い' },
  { id: 'poison', name: '毒', nameEn: 'Venom', icon: 'bug', gem: '#65a30d', gem2: '#bef264', glow: '#84cc16', particle: '#a3e635', metal: '#4d7c0f', shaft: '#2f3b1a', shaft2: '#161d0c', particleStyle: 'bubbles', head: 'spiral-shell', motif: 'drip', shaftStyle: 'coral', halo: 'none', tip: 'eye-tip', wings: 'none', finish: 'glossy', desc: '腐蝕の霧 · 滴る毒液' },
  { id: 'wind', name: '風', nameEn: 'Zephyr', icon: 'wind', gem: '#67e8f9', gem2: '#f0fdfa', glow: '#a5f3fc', particle: '#cffafe', metal: '#cbd5e1', shaft: '#d6d3d1', shaft2: '#78716c', particleStyle: 'leaf', head: 'feather', motif: 'feathers', shaftStyle: 'driftwood', halo: 'spiral', tip: 'plume', wings: 'leafwing', finish: 'matte', desc: '疾風の囁き · 舞う羽根' },
  { id: 'crystal', name: '晶', nameEn: 'Prismatic', icon: 'crystal', gem: '#e879f9', gem2: '#a5f3fc', glow: '#d946ef', particle: '#f5d0fe', metal: '#e2e8f0', shaft: '#f8fafc', shaft2: '#94a3b8', particleStyle: 'diamonds', head: 'tesseract', motif: 'shards', shaftStyle: 'crystal', halo: 'hex-grid', tip: 'crystal-tip', wings: 'crystal', finish: 'holographic', desc: '虹の屈折 · 結晶の共鳴' },
  { id: 'sound', name: '音', nameEn: 'Resonance', icon: 'sound', gem: '#f59e0b', gem2: '#fde68a', glow: '#fbbf24', particle: '#fef3c7', metal: '#b45309', shaft: '#78350f', shaft2: '#3b1c05', particleStyle: 'musical', head: 'chalice', motif: 'notes', shaftStyle: 'braided', halo: 'triple', tip: 'bell', wings: 'none', finish: 'metallic', desc: '響きの波紋 · 鐘の律動' },
  { id: 'time', name: '時', nameEn: 'Chronos', icon: 'clock', gem: '#d4af37', gem2: '#fef9c3', glow: '#eab308', particle: '#fde047', metal: '#a16207', shaft: '#44403c', shaft2: '#1c1917', particleStyle: 'runes', head: 'hourglass', motif: 'clock', shaftStyle: 'techno', halo: 'double', tip: 'orbit-ring', wings: 'mech', finish: 'lacquered', desc: '砂の流転 · 歯車の秩序' },
  { id: 'dream', name: '夢', nameEn: 'Oneiric', icon: 'dream', gem: '#c084fc', gem2: '#fbcfe8', glow: '#e9d5ff', particle: '#f5d0fe', metal: '#a78bfa', shaft: '#4c1d95', shaft2: '#2e1065', particleStyle: 'stars', head: 'dragon-egg', motif: 'petals', shaftStyle: 'braided', halo: 'spiral', tip: 'floating-gem', wings: 'fae', finish: 'frosted', desc: '眠りの帳 · 淡い幻影' },
  { id: 'sakura', name: '桜', nameEn: 'Sakura', icon: 'flower', gem: '#f9a8d4', gem2: '#fbcfe8', glow: '#f472b6', particle: '#fecdd3', metal: '#f9c5d5', shaft: '#783c50', shaft2: '#4c1d2c', particleStyle: 'sparkle', head: 'bloom', motif: 'petals', shaftStyle: 'gnarled', halo: 'none', tip: 'living-bloom', wings: 'fae', finish: 'glossy', desc: '夜の花吹雪 · 淡い春の魔力' },
  { id: 'steel', name: '鋼', nameEn: 'Forged Steel', icon: 'hammer', gem: '#94a3b8', gem2: '#fcd34d', glow: '#d97706', particle: '#e2e8f0', metal: '#e8c874', shaft: '#57534e', shaft2: '#26221f', particleStyle: 'ash', head: 'anvil', motif: 'gears', shaftStyle: 'alloy', halo: 'none', tip: 'blade', wings: 'blade', finish: 'metallic', desc: '鍛造の誇り · 燃える心鉄' },
  { id: 'cosmos', name: '宇宙', nameEn: 'Cosmos', icon: 'orbit', gem: '#6366f1', gem2: '#a5b4fc', glow: '#818cf8', particle: '#c7d2fe', metal: '#b0bec5', shaft: '#1e1b4b', shaft2: '#0d0a26', particleStyle: 'stars', head: 'portal', motif: 'constellation', shaftStyle: 'obsidian', halo: 'hex-grid', tip: 'prism-trio', wings: 'seraph', finish: 'holographic', desc: '銀河の巡星 · 無限の共鳴' },
  { id: 'desert', name: '砂', nameEn: 'Desert', icon: 'mountain', gem: '#f59e0b', gem2: '#fde68a', glow: '#fbbf24', particle: '#fdba74', metal: '#b08968', shaft: '#7c5a35', shaft2: '#4a3721', particleStyle: 'ash', head: 'meteor', motif: 'rock', shaftStyle: 'driftwood', halo: 'sunburst', tip: 'gem-cluster', wings: 'none', finish: 'weathered', desc: '灼熱の地平 · 千年の砂嵐' },
  { id: 'dragon', name: '竜', nameEn: 'Dragon', icon: 'crown', gem: '#ef4444', gem2: '#fca5a5', glow: '#dc2626', particle: '#fca5a5', metal: '#7d7461', shaft: '#44403c', shaft2: '#1c1917', particleStyle: 'embers', head: 'dragon-egg', motif: 'flame', shaftStyle: 'bone', halo: 'none', tip: 'dragon-fang', wings: 'bat', finish: 'lacquered', desc: '古き竜の息吹 · 牙と鱗の威光' },
  { id: 'psyche', name: '霊', nameEn: 'Psyche', icon: 'moon', gem: '#a78bfa', gem2: '#67e8f9', glow: '#c4b5fd', particle: '#99f6e4', metal: '#5eead4', shaft: '#312e81', shaft2: '#161342', particleStyle: 'mixed', head: 'eye', motif: 'wisp', shaftStyle: 'crystal', halo: 'spiral', tip: 'eye-tip', wings: 'fae', finish: 'frosted', desc: '思念の湖面 · 幻惑の光脈' },
  { id: 'foreman', name: '産', nameEn: 'Industrialist', icon: 'hammer', gem: '#d97706', gem2: '#fde68a', glow: '#f59e0b', particle: '#fbbf24', metal: '#b87333', shaft: '#8b5a2b', shaft2: '#3a2313', particleStyle: 'ash', head: 'anvil', motif: 'gears', shaftStyle: 'mech-brass', halo: 'none', tip: 'blade', wings: 'none', finish: 'metallic', desc: '鋼輪の香り · 工業の誇り' },
  { id: 'grove', name: '野', nameEn: 'Wildwood', icon: 'leaf', gem: '#65a30d', gem2: '#a3e635', glow: '#4ade80', particle: '#a5d6a7', metal: '#6b4f2e', shaft: '#6b4f2e', shaft2: '#362716', particleStyle: 'leaf', head: 'feather', motif: 'leaf', shaftStyle: 'oak', halo: 'none', tip: 'cluster', wings: 'leafwing', finish: 'matte', desc: '森林呼吸 · 大地の呼吸' },
  { id: 'gemshine', name: '粋', nameEn: 'Gemshine', icon: 'gem', gem: '#e879f9', gem2: '#a5b4fc', glow: '#d946ef', particle: '#f5d0fe', metal: '#d4af37', shaft: '#f8fafc', shaft2: '#94a3b8', particleStyle: 'diamonds', head: 'octahedron', motif: 'shards', shaftStyle: 'gem-tube', halo: 'triple', tip: 'gem-cluster', wings: 'crystal', finish: 'holographic', desc: '外部は硝子筒 · 光漏れの宝石柱' },
  { id: 'undertow', name: '潮', nameEn: 'Undertow', icon: 'waves', gem: '#06b6d4', gem2: '#a5f3fc', glow: '#22d3ee', particle: '#80deea', metal: '#5eead4', shaft: '#0e7490', shaft2: '#062a36', particleStyle: 'bubbles', head: 'teardrop', motif: 'wave', shaftStyle: 'prismarine', halo: 'ring', tip: 'floating-gem', wings: 'fae', finish: 'glossy', desc: '深淵の暗波 · 再次潮汐の帰り' },
  { id: 'vine', name: '蔓', nameEn: 'Vineyard', icon: 'leaf', gem: '#15803d', gem2: '#86efac', glow: '#22c55e', particle: '#bbf7d0', metal: '#166534', shaft: '#4d7c2a', shaft2: '#1e3510', particleStyle: 'leaf', head: 'glow-berries', motif: 'leaf', shaftStyle: 'mangrove', halo: 'none', tip: 'cluster', wings: 'leafwing', finish: 'vegetal', desc: '茨の蔓 · 湿気の森路地' },
  { id: 'duality', name: '両', nameEn: 'Duality', icon: 'moon', gem: '#8b5cf6', gem2: '#f9a8d4', glow: '#c4b5fd', particle: '#f5d0fe', metal: '#a5b4fc', shaft: '#f8fafc', shaft2: '#312e81', particleStyle: 'mixed', head: 'moonlet', motif: 'jewel-halo', shaftStyle: 'twisted', halo: 'eclipse', tip: 'moon-circlet', wings: 'bat', finish: 'frosted', desc: '光と影 · 陰陽の呼吸' },
  { id: 'pastoral', name: '村', nameEn: 'Pastoral', icon: 'sun', gem: '#f5f0e6', gem2: '#e8dcc0', glow: '#fffde7', particle: '#fef3c7', metal: '#dca35d', shaft: '#dca35d', shaft2: '#8b5a2b', particleStyle: 'plus', head: 'beacon', motif: 'rays', shaftStyle: 'birch', halo: 'ring', tip: 'gem', wings: 'seraph', finish: 'matte', desc: '白日の村路 · 安らぐ田園' },
  { id: 'none', name: '無', nameEn: 'Neutral', icon: 'circle', gem: '#94a3b8', gem2: '#e2e8f0', glow: '#64748b', particle: '#cbd5e1', metal: '#c0c0c0', shaft: '#6b4226', shaft2: '#3d2413', particleStyle: 'sparkle', head: 'orb', motif: 'none', shaftStyle: 'straight', halo: 'none', tip: 'gem', wings: 'none', finish: 'matte', desc: '属性なし · 汎用' },
];

export const getElement = (id: ElementType): ElementDef => ELEMENTS.find((e) => e.id === id) || ELEMENTS[0];

/** Full "re-theme" patch: colors + signature shapes of an element. */
export function applyElement(id: ElementType): Partial<StaffConfig> {
  const e = getElement(id);
  return {
    gemColor: e.gem, gemColor2: e.gem2, glowColor: e.glow, particleColor: e.particle,
    collarColor: e.metal, prongColor: e.metal, pommelColor: e.metal, wrapColor: e.metal,
    shaftColor: e.shaft, shaftColor2: e.shaft2,
    haloColor: e.id === 'light' || e.id === 'arcane' ? '#ffd700' : e.glow,
    particleStyle: e.particleStyle, headShape: e.head, motif: e.motif,
    shaftStyle: e.shaftStyle, halo: e.halo, tipStyle: e.tip, wings: e.wings, finish: e.finish,
  };
}

/** Colors-only patch of an element (used by the randomizer when "colors follow element"). */
export function elementColors(id: ElementType): Partial<StaffConfig> {
  const e = getElement(id);
  return {
    gemColor: e.gem, gemColor2: e.gem2, glowColor: e.glow, particleColor: e.particle,
    collarColor: e.metal, prongColor: e.metal, pommelColor: e.metal, wrapColor: e.metal,
    shaftColor: e.shaft, shaftColor2: e.shaft2,
    haloColor: e.id === 'light' || e.id === 'arcane' ? '#ffd700' : e.glow,
  };
}
