import JSZip from 'jszip';
import { PRESETS } from "./material-presets";
import { fileNameFor, pixelsToBlob, safeName, type MaterialSettings, type Pixels } from "./material-render";
import type { Palette } from "./material-color";
import type { Shape } from "./material-shapes";

export interface PackOptions {
  modId: string;
  scale: number;
  asPack: boolean;
}

export interface RenderedShape {
  shape: Shape;
  pixels: Pixels;
}

const titleCase = (s: string): string =>
  s
    .split('_')
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join(' ');

/** 説明用の括弧を除いた日本語形状名 */
const jaShapeName = (shape: Shape): string => shape.name.replace(/[(（].*?[)）]/g, '').trim();

export function japaneseName(shape: Shape, materialName: string): string {
  const preset = PRESETS.find((p) => p.name === safeName(materialName));
  const mat = preset ? preset.label : materialName;
  const sh = jaShapeName(shape);
  if (shape.file === '{name}') return mat;
  const prefix = shape.file.startsWith('deepslate_') ? '深層' : '';
  if (shape.category === 'block') return `${prefix}${mat}${sh.replace('(深層岩)', '')}`;
  return `${mat}の${sh}`;
}

export function englishName(shape: Shape, materialName: string): string {
  return titleCase(fileNameFor(shape.file, materialName));
}

export async function buildZip(
  rendered: RenderedShape[],
  settings: MaterialSettings,
  palette: Palette,
  opts: PackOptions,
): Promise<Blob> {
  const zip = new JSZip();
  const name = safeName(settings.name);
  const modId = safeName(opts.modId || 'mymod');

  const meta = {
    name,
    modId,
    generatedBy: 'Minecraft Asset Maker',
    settings,
    palette,
    textures: rendered.map((r) => ({
      id: r.shape.id,
      category: r.shape.category,
      file: `${fileNameFor(r.shape.file, settings.name)}.png`,
    })),
  };

  if (!opts.asPack) {
    const folder = zip.folder(name)!;
    for (const { shape, pixels } of rendered) {
      folder.file(`${fileNameFor(shape.file, settings.name)}.png`, await pixelsToBlob(pixels, opts.scale));
    }
    folder.file('material.json', JSON.stringify(meta, null, 2));
    return zip.generateAsync({ type: 'blob' });
  }

  const en: Record<string, string> = {};
  const ja: Record<string, string> = {};
  for (const { shape, pixels } of rendered) {
    const file = fileNameFor(shape.file, settings.name);
    const kind = shape.category === 'block' ? 'block' : 'item';
    zip.file(`assets/${modId}/textures/${kind}/${file}.png`, await pixelsToBlob(pixels, opts.scale));
    en[`${kind}.${modId}.${file}`] = englishName(shape, settings.name);
    ja[`${kind}.${modId}.${file}`] = japaneseName(shape, settings.name);
  }
  zip.file(`assets/${modId}/lang/en_us.json`, JSON.stringify(en, null, 2));
  zip.file(`assets/${modId}/lang/ja_jp.json`, JSON.stringify(ja, null, 2));
  zip.file(
    'pack.mcmeta',
    JSON.stringify(
      {
        pack: {
          pack_format: 34,
          description: `${titleCase(name)} textures (Minecraft Asset Maker)`,
        },
      },
      null,
      2,
    ),
  );
  zip.file('material.json', JSON.stringify(meta, null, 2));
  zip.file(
    'README.txt',
    [
      `${titleCase(name)} — generated by Minecraft Asset Maker`,
      '',
      `assets/${modId}/textures/item/   … アイテム用テクスチャ`,
      `assets/${modId}/textures/block/  … ブロック用テクスチャ`,
      `assets/${modId}/lang/            … 表示名 (en_us / ja_jp)`,
      'pack.mcmeta                      … pack_format 34 (1.21 系)。他バージョンでは数値を変更してください',
      '',
      'Mod で使う場合は assets/ 以下を src/main/resources/ にコピーしてください。',
    ].join('\n'),
  );
  return zip.generateAsync({ type: 'blob' });
}
