// ============================================================
// データパック(.zip)生成
// バージョンごとのフォルダ名・pack_format を自動で切り替える
// ============================================================
import { strToU8, zipSync } from "fflate";
import type { ValidationResult } from "./structure-ops";

/** 1.21以降は data/<ns>/structure/、1.20.x以前は structures/ */
export function structureFolderFor(dataVersion: number): string {
  return dataVersion >= 3953 ? "structure" : "structures";
}

export function packFormatFor(dv: number): number {
  if (dv >= 4189) return 61; // 1.21.4
  if (dv >= 3953) return 48; // 1.21 / 1.21.1
  if (dv >= 3837) return 41; // 1.20.5 / 1.20.6
  if (dv >= 3700) return 26; // 1.20.4
  if (dv >= 3578) return 18; // 1.20.2
  if (dv >= 3465) return 15; // 1.20.1
  return 12; // 1.19.4 以前
}

export interface DatapackInput {
  packName: string;
  namespace: string;
  structName: string;
  nbt: Uint8Array;
  dataVersion: number;
  validation: ValidationResult;
  author: string;
}

export function buildDatapackZip(input: DatapackInput): Uint8Array {
  const { packName, namespace, structName, nbt, dataVersion, validation, author } = input;
  const folder = structureFolderFor(dataVersion);
  const mcmeta = {
    pack: {
      pack_format: packFormatFor(dataVersion),
      description: `${packName} — generated by Minecraft Asset Maker (${author})`,
    },
  };

  const modLines =
    validation.namespaces.length > 0
      ? validation.namespaces
          .map((n) => `  - ${n.ns}${n.ns === "minecraft" ? "" : "  ← MODが必要"} (${n.count}個)`)
          .join("\n")
      : "  - (ブロックなし)";
  const unregLines =
    validation.unregistered.length > 0
      ? validation.unregistered.map((u) => `  - ${u.id} (${u.count}個)`).join("\n")
      : "  - なし";

  const readme = [
    `${packName}`,
    "=".repeat(packName.length),
    "",
    "[配置方法]",
    `  data/${namespace}/${folder}/${structName}.nbt を配置してください。`,
    "",
    "[ゲーム内での呼び出し]",
    `  /place structure ${namespace}:${structName} ~ ~ ~`,
    "  (データパック有効化後、/reload)",
    "",
    "[必要なMod / 名前空間]",
    modLines,
    "",
    "[未登録ブロックID（Modが無いと空気になります）]",
    unregLines,
    "",
    "[不正なID]",
    validation.invalid.length ? validation.invalid.map((i) => `  - ${i}`).join("\n") : "  - なし",
    "",
    "Generated by Minecraft Asset Maker",
  ].join("\n");

  const files: Record<string, Uint8Array> = {
    [`${packName}/pack.mcmeta`]: strToU8(JSON.stringify(mcmeta, null, 2)),
    [`${packName}/data/${namespace}/${folder}/${structName}.nbt`]: nbt,
    [`${packName}/README.txt`]: strToU8(readme),
  };
  return zipSync(files, { level: 6 });
}
