import JSZip from "jszip";

export type PackTarget = "java" | "bedrock";
export type PackKind = "block" | "item";

export interface PackFile {
  path: string;
  text?: string;
  base64?: string;
  language: "json" | "markdown" | "image" | "text";
}

export interface PackInput {
  modelName: string;
  namespace: string;
  friendlyName: string;
  kind: PackKind;
  javaJson: string;
  bedrockJson: string;
  textureDataUrl: string;
  previewDataUrl: string;
  textureWidth: number;
  textureHeight: number;
  cubeCount: number;
  reductionPercent: number;
}

function safeSegment(value: string): string {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9_]+/g, "_")
      .replace(/^_+|_+$/g, "") || "voxel_asset"
  );
}

function parseJson(text: string): unknown {
  try {
    return JSON.parse(text);
  } catch {
    return {};
  }
}

function pngBase64(dataUrl: string): string {
  return dataUrl.includes(",") ? dataUrl.split(",")[1] : dataUrl;
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  return `${(bytes / 1024).toFixed(1)} KB`;
}

/** Item model that simply parents to the block model — matches vanilla conventions. */
function itemModelFromBlock(namespace: string, name: string, display: unknown) {
  return {
    parent: `${namespace}:block/${name}`,
    ...(display && typeof display === "object" ? { display } : {}),
  };
}

export function buildJavaPack(input: PackInput): PackFile[] {
  const name = safeSegment(input.modelName);
  const ns = safeSegment(input.namespace || "custom");
  const model = parseJson(input.javaJson) as {
    elements?: unknown[];
    display?: unknown;
    ambientocclusion?: boolean;
    texture_size?: number[];
  };
  const elements = model.elements ?? [];
  const display = model.display ?? {};

  const geometry = {
    credit: "Generated with Voxel Forge Studio",
    ambientocclusion: model.ambientocclusion ?? true,
    texture_size: [input.textureWidth, input.textureHeight],
    textures: { "0": `${ns}:block/${name}`, particle: `${ns}:block/${name}` },
    elements,
  };

  const itemGeometry = {
    credit: "Generated with Voxel Forge Studio",
    ambientocclusion: model.ambientocclusion ?? true,
    texture_size: [input.textureWidth, input.textureHeight],
    textures: { "0": `${ns}:item/${name}`, particle: `${ns}:item/${name}` },
    elements,
    display,
  };

  const files: PackFile[] = [
    {
      path: "pack.mcmeta",
      language: "json",
      text: JSON.stringify(
        {
          pack: {
            pack_format: 18,
            supported_formats: { min_inclusive: 12, max_inclusive: 999 },
            description: `${input.friendlyName} — generated by Voxel Forge Studio`,
          },
        },
        null,
        2,
      ),
    },
    {
      path: "assets/minecraft/lang/en_us.json",
      language: "json",
      text: JSON.stringify(
        input.kind === "block"
          ? { [`block.${ns}.${name}`]: input.friendlyName }
          : { [`item.${ns}.${name}`]: input.friendlyName },
        null,
        2,
      ),
    },
    {
      path: `assets/${ns}/textures/${input.kind}/${name}.png`,
      language: "image",
      base64: pngBase64(input.textureDataUrl),
    },
    {
      path: "pack.png",
      language: "image",
      base64: pngBase64(input.previewDataUrl || input.textureDataUrl),
    },
  ];

  if (input.kind === "block") {
    files.push(
      {
        path: `assets/${ns}/models/block/${name}.json`,
        language: "json",
        text: JSON.stringify(geometry, null, 2),
      },
      {
        path: `assets/${ns}/blockstates/${name}.json`,
        language: "json",
        text: JSON.stringify(
          { variants: { "": { model: `${ns}:block/${name}` } } },
          null,
          2,
        ),
      },
      {
        path: `assets/${ns}/models/item/${name}.json`,
        language: "json",
        text: JSON.stringify(
          itemModelFromBlock(ns, name, {
            gui: { rotation: [30, 225, 0], scale: [0.625, 0.625, 0.625] },
            ground: { scale: [0.25, 0.25, 0.25] },
            fixed: { scale: [0.5, 0.5, 0.5] },
          }),
          null,
          2,
        ),
      },
      {
        path: `data/${ns}/recipe/${name}.json`,
        language: "json",
        text: JSON.stringify(
          {
            type: "minecraft:crafting_shaped",
            category: "building",
            pattern: ["##", "##"],
            key: { "#": { item: "minecraft:stone" } },
            result: { id: `${ns}:${name}`, count: 1 },
            __note: "サンプルレシピです。素材は必要に合わせて書き換えてください",
          },
          null,
          2,
        ),
      },
    );
  } else {
    files.push({
      path: `assets/${ns}/models/item/${name}.json`,
      language: "json",
      text: JSON.stringify(itemGeometry, null, 2),
    });
  }

  files.push({
    path: "VOXELFORGE.md",
    language: "markdown",
    text: [
      `# ${input.friendlyName}`,
      "",
      "Voxel Forge Studio が生成した Java Edition リソースパックです。",
      "",
      "## 構成",
      `- モデル: ${elements.length} キューブ（グリーディ統合後）`,
      `- テクスチャ: ${input.textureWidth}×${input.textureHeight} px`,
      `- 名前空間: \`${ns}\``,
      "",
      "## 導入手順",
      "1. このフォルダを zip に圧縮したものを `resourcepacks/` へ置きます",
      "2. `表示設定 → リソースパック` で有効化",
      input.kind === "block"
        ? "3. ブロックは `blockstates/` 経由で参照されます"
        : "3. アイテムは `models/item/` 直下で参照されます",
      "",
      "## 手直しポイント",
      "- `pack_format` は対象バージョンに合わせてください（18 = 1.20 系、22 = 1.21 系など）",
      "- ブロックとして配置する場合、`models/block` の要素は 0〜16 の範囲に収める必要があります",
      "- 発光ピクセルは OptiFine の emissive textures と組み合わせると暗所でも光ります",
    ].join("\n"),
  });

  return files;
}

export function buildBedrockPack(input: PackInput): PackFile[] {
  const name = safeSegment(input.modelName);
  const ns = safeSegment(input.namespace || "custom");
  const folder = `${ns}_${name}`;

  return [
    {
      path: "manifest.json",
      language: "json",
      text: JSON.stringify(
        {
          format_version: 2,
          header: {
            name: `${input.friendlyName} RP`,
            description: "Generated by Voxel Forge Studio",
            uuid: cryptoUuid(),
            version: [1, 0, 0],
            min_engine_version: [1, 20, 0],
          },
          modules: [
            { type: "resources", uuid: cryptoUuid(), version: [1, 0, 0] },
          ],
        },
        null,
        2,
      ),
    },
    {
      path: `textures/${input.kind === "block" ? "terrain_texture" : "item_texture"}.json`,
      language: "json",
      text: JSON.stringify(
        {
          resource_pack_name: folder,
          texture_name:
            input.kind === "block" ? "atlas.terrain" : "atlas.items",
          padding: 8,
          num_mip_levels: 4,
          texture_data: {
            [`${ns}.${name}`]: {
              textures: `textures/${input.kind === "block" ? "blocks" : "items"}/${name}.png`,
            },
          },
        },
        null,
        2,
      ),
    },
    {
      path: `models/${name}.geo.json`,
      language: "json",
      text: JSON.stringify(parseJson(input.bedrockJson), null, 2),
    },
    ...(input.kind === "block"
      ? [
          {
            path: "blocks.json",
            language: "json" as const,
            text: JSON.stringify(
              {
                format_version: [1, 1, 0],
                [`${ns}:${name}`]: { textures: `${ns}.${name}`, sound: "stone" },
              },
              null,
              2,
            ),
          },
        ]
      : []),
    {
      path: `textures/${input.kind === "block" ? "blocks" : "items"}/${name}.png`,
      language: "image",
      base64: pngBase64(input.textureDataUrl),
    },
    {
      path: "pack.png",
      language: "image",
      base64: pngBase64(input.previewDataUrl || input.textureDataUrl),
    },
    {
      path: "VOXELFORGE.md",
      language: "markdown",
      text: [
        `# ${input.friendlyName} (Bedrock)`,
        "",
        "Voxel Forge Studio が生成した Bedrock Edition リソースパックです。",
        "",
        "## 導入手順",
        "1. フォルダごと `development_resource_packs/` へ置きます",
        "2. ワールド設定でリソースパックを有効化",
        `3. geometry ID: \`geometry.${name}\``,
        "",
        "## 注意",
        input.kind === "block"
          ? "- `blocks.json` を同梱済みです。カスタムブロックとして配置するには行動パック側の定義も必要です"
          : "- アイテムとして使う場合は behavior pack の `minecraft:item` で `icon` を `textures/items/" + name + "` に指定してください",
        "- モデルをエンティティに使う場合は client entity JSON 側の `geometry` を上記 ID に合わせてください",
        `- テクスチャ: ${input.textureWidth}×${input.textureHeight} px / ${input.cubeCount} キューブ`,
      ].join("\n"),
    },
  ];
}

function cryptoUuid(): string {
  const c = globalThis.crypto as Crypto | undefined;
  if (c?.randomUUID) return c.randomUUID();
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (ch) => {
    const r = Math.floor(Math.random() * 16);
    return (ch === "x" ? r : (r & 0x3) | 0x8).toString(16);
  });
}

export function packFileLabel(path: string): string {
  return path.split("/").pop() ?? path;
}

export interface PackTreeNode {
  name: string;
  path: string;
  children: PackTreeNode[];
  file?: PackFile;
  size: number;
}

function fileSize(file: PackFile): number {
  if (file.text) return new Blob([file.text]).size;
  if (file.base64) return Math.round((file.base64.length * 3) / 4);
  return 0;
}

export function buildPackTree(files: PackFile[]): PackTreeNode[] {
  const root: PackTreeNode = { name: "", path: "", children: [], size: 0 };

  files.forEach((file) => {
    const parts = file.path.split("/");
    let cursor = root;
    parts.forEach((part, index) => {
      const isLeaf = index === parts.length - 1;
      const path = parts.slice(0, index + 1).join("/");
      let next = cursor.children.find((child) => child.name === part);
      if (!next) {
        next = { name: part, path, children: [], size: 0 };
        cursor.children.push(next);
      }
      if (isLeaf) next.file = file;
      cursor = next;
    });
  });

  const finalize = (node: PackTreeNode): PackTreeNode => {
    node.children.sort((a, b) => {
      const aFolder = a.children.length > 0 ? 0 : 1;
      const bFolder = b.children.length > 0 ? 0 : 1;
      if (aFolder !== bFolder) return aFolder - bFolder;
      return a.name.localeCompare(b.name);
    });
    node.children.forEach(finalize);
    node.size = node.file
      ? fileSize(node.file)
      : node.children.reduce((sum, child) => sum + child.size, 0);
    return node;
  };

  return finalize(root).children;
}

export function packTotalSize(files: PackFile[]): string {
  return formatBytes(files.reduce((sum, file) => sum + fileSize(file), 0));
}

export async function zipPackFiles(files: PackFile[]): Promise<Blob> {
  const zip = new JSZip();
  files.forEach((file) => {
    if (file.base64) zip.file(file.path, file.base64, { base64: true });
    else if (file.text) zip.file(file.path, file.text);
  });
  return zip.generateAsync({ type: "blob", compression: "DEFLATE" });
}

export { formatBytes };
