import type { Template } from "./model-types";

/** Single source for template categories, dimensions, motion defaults and vanilla item mappings. */
export const TEMPLATE_CATALOG: Template[] = [
  {
    kind: "sword",
    label: "剣",
    english: "Sword",
    category: "classic",
    name: "クリスタルソード",
    prompt:
      "透き通るクリスタルの刀身と、ダークメタルの鍔。柄には紫のレザーを巻き、ファンタジーの世界に合う剣に。",
    dimensions: [16, 32, 4],
    vanillaItem: "diamond_sword",
  },
  {
    kind: "pickaxe",
    label: "ツルハシ",
    english: "Pickaxe",
    category: "classic",
    name: "クリスタルピッケル",
    prompt:
      "ダイヤモンドの刃と丈夫な柄。先端が鋭く、鉱石の輝きを感じるファンタジーのツルハシ。",
    dimensions: [16, 32, 4],
    vanillaItem: "diamond_pickaxe",
  },
  {
    kind: "axe",
    label: "斧",
    english: "Axe",
    category: "classic",
    name: "エメラルドアックス",
    prompt:
      "エメラルドに輝く大きな刃、ダークメタルのフレームと革巻きの柄を持つ斧。",
    dimensions: [16, 32, 4],
    vanillaItem: "diamond_axe",
  },
  {
    kind: "shield",
    label: "盾",
    english: "Shield",
    category: "classic",
    name: "古代のルーンシールド",
    prompt:
      "紫のクリスタルを中央に埋め込み、金色の縁取りと古代のルーンをあしらった盾。",
    dimensions: [16, 24, 4],
    vanillaItem: "paper",
  },
  {
    kind: "staff",
    label: "杖",
    english: "Staff",
    category: "arcane",
    name: "アメジストの杖",
    prompt:
      "紫のアメジストを先端に浮かべた魔法の杖。長い柄に金色の装飾と小さな宝石。",
    dimensions: [16, 32, 4],
    vanillaItem: "stick",
    defaults: { floaters: "crystal", effect: "glow", animation: "float" },
  },
  {
    kind: "block",
    label: "ブロック",
    english: "Block",
    category: "classic",
    name: "クリスタルブロック",
    prompt:
      "深い青緑の鉱石を含む装飾ブロック。表面にクリスタルの模様と金色のライン。",
    dimensions: [16, 16, 16],
    vanillaItem: "paper",
  },
  {
    kind: "drill",
    label: "ドリル",
    english: "Drill",
    category: "mechanical",
    name: "ギアドリル",
    prompt: "回転するギアと鋼鉄のドリル。火花を散らす機械的な近接武器。",
    dimensions: [14, 30, 14],
    vanillaItem: "iron_pickaxe",
    defaults: {
      floaters: "orbit",
      effect: "sparkle",
      animation: "spin",
      action: "spin",
    },
  },
  {
    kind: "cannon",
    label: "キャノン",
    english: "Cannon",
    category: "mechanical",
    name: "魔導キャノン",
    prompt: "青白い光を溜める機械の砲身。ギアと銅のパイプが並ぶ魔導兵器。",
    dimensions: [14, 30, 12],
    vanillaItem: "crossbow",
    defaults: { floaters: "orbit", effect: "glow", action: "charge" },
  },
  {
    kind: "mechblade",
    label: "機刃",
    english: "Mecha Blade",
    category: "mechanical",
    name: "起動式機刃",
    prompt:
      "折りたたまれた刃が展開する機械の剣。ネオンの発光ラインと金属の装甲。",
    dimensions: [12, 32, 6],
    vanillaItem: "iron_sword",
    defaults: { floaters: "crystal", effect: "magic", action: "transform" },
  },
  {
    kind: "runeblade",
    label: "魔法剣",
    english: "Rune Blade",
    category: "arcane",
    name: "星詠みのルーンブレード",
    prompt: "紫の魔法剣。白金のフレームに封じた星の結晶と、宙に浮くルーン。",
    dimensions: [14, 32, 5],
    vanillaItem: "diamond_sword",
    defaults: {
      effect: "runes",
      animation: "orbit",
      floaters: "orbit",
      action: "cast",
    },
  },
  {
    kind: "cursedblade",
    label: "禍刃",
    english: "Abyss Blade",
    category: "dark",
    name: "深淵の禍刃",
    prompt: "禍々しい黒曜石の刃。曲がった角、鋸状の棘、紫の邪眼と呪印。",
    dimensions: [16, 32, 5],
    vanillaItem: "netherite_sword",
    defaults: { effect: "void", animation: "pulse", floaters: "swarm" },
  },
  {
    kind: "bloodblade",
    label: "血晶剣",
    english: "Blood Blade",
    category: "dark",
    name: "紅月の血晶剣",
    prompt: "ブラッドの赤い結晶剣。血晶の脈動、黒い骨格、真紅の紋章。",
    dimensions: [14, 32, 4],
    vanillaItem: "netherite_sword",
    defaults: { effect: "blood", animation: "pulse", action: "slash" },
  },
  {
    kind: "elderstaff",
    label: "賢者の杖",
    english: "Astral Staff",
    category: "arcane",
    name: "天球の賢者杖",
    prompt: "青い星を包む二重の天球儀。金の装飾と螺旋のルーンを持つ賢者の杖。",
    dimensions: [16, 36, 9],
    vanillaItem: "stick",
    defaults: {
      floaters: "orbit",
      animation: "orbit",
      effect: "runes",
      action: "summon",
    },
  },
  {
    kind: "bloodstaff",
    label: "血月の杖",
    english: "Bloodmoon Staff",
    category: "dark",
    name: "血月の儀式杖",
    prompt: "ブラッドの儀式杖。赤い三日月、禍々しい角、鎖に繋がれた血晶。",
    dimensions: [16, 34, 6],
    vanillaItem: "stick",
    defaults: {
      floaters: "crystal",
      animation: "pulse",
      effect: "blood",
      action: "ritual",
    },
  },
  {
    kind: "grimoire",
    label: "魔導書",
    english: "Grimoire",
    category: "arcane",
    name: "星辰の魔導書",
    prompt:
      "紫の魔導書。開いた古いページに光るルーン、金の角飾り、浮遊する封印。",
    dimensions: [24, 18, 8],
    vanillaItem: "book",
    defaults: {
      floaters: "orbit",
      effect: "runes",
      animation: "float",
      action: "ritual",
    },
  },
  {
    kind: "magiccircle",
    label: "魔法陣",
    english: "Magic Circle",
    category: "arcane",
    name: "六芒の召喚陣",
    prompt: "青い二重の魔法陣。六芒星とルーン、外周に浮遊する結晶。",
    dimensions: [26, 26, 3],
    vanillaItem: "paper",
    defaults: {
      effect: "runes",
      floaters: "orbit",
      animation: "spin",
      action: "summon",
    },
  },
  {
    kind: "bow",
    label: "弓",
    english: "Celestial Bow",
    category: "classic",
    name: "月光の弓",
    prompt:
      "エメラルドの飾りをあしらった精霊の弓。金のアームと張りつめた光の弦。",
    dimensions: [18, 32, 5],
    vanillaItem: "bow",
    defaults: { effect: "glow", action: "draw" },
  },
  {
    kind: "rifle",
    label: "ライフル",
    english: "Tactical Rifle",
    category: "modern",
    name: "A-17 タクティカルライフル",
    prompt:
      "鋼鉄の近代ライフル。レール、スコープ、マガジン、冷却用のベントと精密な装甲。",
    dimensions: [30, 14, 5],
    vanillaItem: "crossbow",
    defaults: { action: "shoot", effect: "embers" },
  },
  {
    kind: "pistol",
    label: "銃",
    english: "Arc Pistol",
    category: "modern",
    name: "アークピストル",
    prompt:
      "鋼鉄の銃。コンパクトなスライド、発光サイト、真鍮のトリガーと冷却口。",
    dimensions: [22, 16, 5],
    vanillaItem: "crossbow",
    defaults: { action: "shoot", effect: "electric" },
  },
  {
    kind: "railgun",
    label: "レールガン",
    english: "Railgun",
    category: "modern",
    name: "R-09 レールガン",
    prompt:
      "機械のレールガン。2本の導体レール、青いコイルと宙に浮いた蓄電コア。",
    dimensions: [32, 14, 7],
    vanillaItem: "crossbow",
    defaults: { action: "charge", effect: "electric" },
  },
  {
    kind: "chainsaw",
    label: "チェーンソー",
    english: "Chainsaw",
    category: "mechanical",
    name: "ギアファング・チェーンソー",
    prompt:
      "機械式チェーンソー。銅のエンジン、鋸歯のチェーンと排気管、防護ハンドル。",
    dimensions: [14, 32, 7],
    vanillaItem: "iron_axe",
    defaults: { action: "rev", effect: "embers" },
  },
  {
    kind: "relic",
    label: "レリック",
    english: "Relic",
    category: "arcane",
    name: "黎明のレリック",
    prompt:
      "金の古代レリック。聖なる幾何学の籠、白い心臓の結晶と浮遊する紋章。",
    dimensions: [18, 26, 12],
    vanillaItem: "amethyst_shard",
    defaults: {
      effect: "runes",
      floaters: "orbit",
      animation: "orbit",
      action: "summon",
    },
  },
  {
    kind: "spear",
    label: "装飾スピア",
    english: "Regal Spear",
    category: "classic",
    name: "王冠のセレモニアルスピア",
    prompt:
      "紫の結晶を頂く豪華なスピア。翼の鍔、王冠、金の細工、宝石、鎖、房飾り。",
    dimensions: [16, 38, 5],
    vanillaItem: "trident",
    defaults: { effect: "glow", action: "thrust" },
  },
  {
    kind: "mace",
    label: "メイス",
    english: "Royal Mace",
    category: "classic",
    name: "雷冠のメイス",
    prompt: "鋼鉄のメイス。6枚のフランジ、金の紋章と青い雷晶、鎖と装飾の柄。",
    dimensions: [14, 30, 11],
    vanillaItem: "mace",
    defaults: { effect: "electric", action: "slam" },
  },
];
