import type { Rarity } from "@/lib/rarity";

export const CATEGORY_IDS = [
  "sword",
  "bow",
  "staff",
  "armor",
  "tool",
  "accessory",
  "pet",
  "minion",
  "misc",
] as const;

export type Category = (typeof CATEGORY_IDS)[number];

export const CATEGORIES: Record<Category, { label: string; labelJa: string; icon: string }> = {
  sword: { label: "Swords", labelJa: "剣", icon: "⚔" },
  bow: { label: "Bows", labelJa: "弓", icon: "🏹" },
  staff: { label: "Staves", labelJa: "杖", icon: "⚚" },
  armor: { label: "Armor", labelJa: "防具", icon: "🛡" },
  tool: { label: "Tools", labelJa: "道具", icon: "⛏" },
  accessory: { label: "Accessories", labelJa: "アクセサリー", icon: "💍" },
  pet: { label: "Pets", labelJa: "ペット", icon: "🐉" },
  minion: { label: "Minions", labelJa: "ミニオン", icon: "♟" },
  misc: { label: "Misc", labelJa: "その他", icon: "✦" },
};

export type CatalogItem = {
  id: string;
  name: string;
  nameJa: string;
  category: Category;
  templates: string[];
  rarity: Rarity;
  mcItems: string[];
  citPattern: string;
  lore: string;
  tags: string[];
};

export const CATALOG: CatalogItem[] = [
  {
    id: "hyperion",
    name: "Hyperion",
    nameJa: "ハイピリオン",
    category: "sword",
    templates: ["sword_wither", "sword_long"],
    rarity: "legendary",
    mcItems: ["diamond_sword"],
    citPattern: "Hyperion",
    lore: "ウィザーブレイド。爆発とテレポートの象徴。",
    tags: ["dungeon", "mage", "wither"],
  },
  {
    id: "astraea",
    name: "Astraea",
    nameJa: "アストレア",
    category: "sword",
    templates: ["sword_wither", "sword_great"],
    rarity: "legendary",
    mcItems: ["diamond_sword"],
    citPattern: "Astraea",
    lore: "防御寄りのウィザーブレイド。",
    tags: ["dungeon", "tank", "wither"],
  },
  {
    id: "scylla",
    name: "Scylla",
    nameJa: "スキュラ",
    category: "sword",
    templates: ["sword_wither", "sword_rapier"],
    rarity: "legendary",
    mcItems: ["diamond_sword"],
    citPattern: "Scylla",
    lore: "クリティカルに特化した一振り。",
    tags: ["dungeon", "crit", "wither"],
  },
  {
    id: "valkyrie",
    name: "Valkyrie",
    nameJa: "ヴァルキリー",
    category: "sword",
    templates: ["sword_wither", "sword_broad"],
    rarity: "legendary",
    mcItems: ["diamond_sword"],
    citPattern: "Valkyrie",
    lore: "戦士のウィザーブレイド。",
    tags: ["dungeon", "berserk", "wither"],
  },
  {
    id: "dark_claymore",
    name: "Dark Claymore",
    nameJa: "ダーククレイモア",
    category: "sword",
    templates: ["sword_great"],
    rarity: "legendary",
    mcItems: ["stone_sword", "iron_sword"],
    citPattern: "Dark Claymore",
    lore: "両手持ちの巨大剣。影が刃になる。",
    tags: ["dungeon", "berserk"],
  },
  {
    id: "giants_sword",
    name: "Giant's Sword",
    nameJa: "ジャイアンツソード",
    category: "sword",
    templates: ["sword_great", "sword_long"],
    rarity: "legendary",
    mcItems: ["iron_sword", "golden_sword"],
    citPattern: "Giant's Sword",
    lore: "巨人の骨から鍛えられた大剣。",
    tags: ["dungeon", "berserk"],
  },
  {
    id: "livid_dagger",
    name: "Livid Dagger",
    nameJa: "リビッドダガー",
    category: "sword",
    templates: ["sword_dagger", "sword_rapier"],
    rarity: "legendary",
    mcItems: ["iron_sword", "diamond_sword"],
    citPattern: "Livid Dagger",
    lore: "背後を狙う暗殺者の短剣。",
    tags: ["dungeon", "assassin"],
  },
  {
    id: "shadow_fury",
    name: "Shadow Fury",
    nameJa: "シャドウフューリー",
    category: "sword",
    templates: ["sword_long", "sword_dagger"],
    rarity: "legendary",
    mcItems: ["diamond_sword"],
    citPattern: "Shadow Fury",
    lore: "影を駆け、複数の敵を貫く。",
    tags: ["dungeon", "assassin"],
  },
  {
    id: "aspect_of_the_dragons",
    name: "Aspect of the Dragons",
    nameJa: "アスペクト・オブ・ザ・ドラゴンズ",
    category: "sword",
    templates: ["sword_long", "sword_broad"],
    rarity: "legendary",
    mcItems: ["diamond_sword"],
    citPattern: "Aspect of the Dragons",
    lore: "ドラゴンの息を乗せる古典の名剣。",
    tags: ["dragon", "classic"],
  },
  {
    id: "aspect_of_the_void",
    name: "Aspect of the Void",
    nameJa: "アスペクト・オブ・ザ・ヴォイド",
    category: "sword",
    templates: ["sword_broad", "sword_rapier"],
    rarity: "epic",
    mcItems: ["diamond_sword"],
    citPattern: "Aspect of the Void",
    lore: "虚空を折りたたんで瞬移する。",
    tags: ["end", "utility"],
  },
  {
    id: "flower_of_truth",
    name: "Flower of Truth",
    nameJa: "フラワー・オブ・トゥルース",
    category: "sword",
    templates: ["sword_long", "sword_scythe"],
    rarity: "legendary",
    mcItems: ["diamond_sword", "red_tulip"],
    citPattern: "Flower of Truth",
    lore: "薔薇が飛び、真実を裂く。",
    tags: ["dungeon", "mage"],
  },
  {
    id: "frozen_scythe",
    name: "Frozen Scythe",
    nameJa: "フローズンサイズ",
    category: "sword",
    templates: ["sword_scythe"],
    rarity: "rare",
    mcItems: ["diamond_hoe", "iron_hoe"],
    citPattern: "Frozen Scythe",
    lore: "氷の弧を投げる大鎌。",
    tags: ["ice", "mage"],
  },
  {
    id: "axe_of_the_shredded",
    name: "Axe of the Shredded",
    nameJa: "アックス・オブ・ザ・シュレッデッド",
    category: "sword",
    templates: ["tool_axe", "sword_great"],
    rarity: "legendary",
    mcItems: ["diamond_axe"],
    citPattern: "Axe of the Shredded",
    lore: "ゾンビを挽くための儀式斧。",
    tags: ["undead", "berserk"],
  },
  {
    id: "reaper_falchion",
    name: "Reaper Falchion",
    nameJa: "リーパーファルシオン",
    category: "sword",
    templates: ["sword_long", "sword_scythe"],
    rarity: "epic",
    mcItems: ["diamond_sword", "golden_sword"],
    citPattern: "Reaper Falchion",
    lore: "死神の湾刀。アンデッド特効。",
    tags: ["undead"],
  },
  {
    id: "midas_sword",
    name: "Midas' Sword",
    nameJa: "ミダスソード",
    category: "sword",
    templates: ["sword_long", "sword_great"],
    rarity: "legendary",
    mcItems: ["golden_sword"],
    citPattern: "Midas' Sword",
    lore: "払った金貨の枚数が刃になる。",
    tags: ["gold", "classic"],
  },
  {
    id: "terminator",
    name: "Terminator",
    nameJa: "ターミネーター",
    category: "bow",
    templates: ["bow_heavy", "bow_crossbow"],
    rarity: "legendary",
    mcItems: ["bow"],
    citPattern: "Terminator",
    lore: "三本の矢を同時に放つ終末の弓。",
    tags: ["dungeon", "archer"],
  },
  {
    id: "juju_shortbow",
    name: "Juju Shortbow",
    nameJa: "ジュジュショートボウ",
    category: "bow",
    templates: ["bow_short", "bow_long"],
    rarity: "epic",
    mcItems: ["bow"],
    citPattern: "Juju Shortbow",
    lore: "速射の短弓。アーチャーの通過儀礼。",
    tags: ["archer"],
  },
  {
    id: "last_breath",
    name: "Last Breath",
    nameJa: "ラストブレス",
    category: "bow",
    templates: ["bow_long", "bow_short"],
    rarity: "epic",
    mcItems: ["bow"],
    citPattern: "Last Breath",
    lore: "守護を削る最後の息。",
    tags: ["dungeon", "archer"],
  },
  {
    id: "mosquito_bow",
    name: "Mosquito Bow",
    nameJa: "モスキートボウ",
    category: "bow",
    templates: ["bow_long"],
    rarity: "legendary",
    mcItems: ["bow"],
    citPattern: "Mosquito Bow",
    lore: "生命を吸う羽音の弓。",
    tags: ["arachne", "archer"],
  },
  {
    id: "spirit_bow",
    name: "Spirit Bow",
    nameJa: "スピリットボウ",
    category: "bow",
    templates: ["bow_short", "bow_long"],
    rarity: "epic",
    mcItems: ["bow"],
    citPattern: "Spirit Bow",
    lore: "地下墓地に響く霊弓。",
    tags: ["dungeon"],
  },
  {
    id: "runaans_bow",
    name: "Runaan's Bow",
    nameJa: "ルナーンボウ",
    category: "bow",
    templates: ["bow_long"],
    rarity: "legendary",
    mcItems: ["bow"],
    citPattern: "Runaan's Bow",
    lore: "分岐する魔力の矢。",
    tags: ["archer", "classic"],
  },
  {
    id: "spirit_sceptre",
    name: "Spirit Sceptre",
    nameJa: "スピリットセプター",
    category: "staff",
    templates: ["staff_sceptre", "staff_wand"],
    rarity: "legendary",
    mcItems: ["bone", "blaze_rod"],
    citPattern: "Spirit Sceptre",
    lore: "蝙蝠を放つ霊杖。",
    tags: ["dungeon", "mage"],
  },
  {
    id: "bonzo_staff",
    name: "Bonzo's Staff",
    nameJa: "ボンゾスタッフ",
    category: "staff",
    templates: ["staff_wand", "staff_sceptre"],
    rarity: "rare",
    mcItems: ["blaze_rod", "stick"],
    citPattern: "Bonzo's Staff",
    lore: "風船をぶつける道化の杖。",
    tags: ["dungeon", "mage"],
  },
  {
    id: "midas_staff",
    name: "Midas' Staff",
    nameJa: "ミダススタッフ",
    category: "staff",
    templates: ["staff_sceptre", "staff_orb"],
    rarity: "legendary",
    mcItems: ["golden_shovel", "blaze_rod"],
    citPattern: "Midas' Staff",
    lore: "金の塊を降らせる呪杖。",
    tags: ["gold", "mage"],
  },
  {
    id: "fire_veil_wand",
    name: "Fire Veil Wand",
    nameJa: "ファイアヴェールワンド",
    category: "staff",
    templates: ["staff_wand"],
    rarity: "epic",
    mcItems: ["blaze_rod"],
    citPattern: "Fire Veil Wand",
    lore: "炎のヴェールを身にまとう。",
    tags: ["crimson", "mage"],
  },
  {
    id: "wand_of_atonement",
    name: "Wand of Atonement",
    nameJa: "ワンド・オブ・アトーンメント",
    category: "staff",
    templates: ["staff_wand"],
    rarity: "epic",
    mcItems: ["stick", "blaze_rod"],
    citPattern: "Wand of Atonement",
    lore: "自己回復の最終形。",
    tags: ["healing"],
  },
  {
    id: "necron_helmet",
    name: "Necron's Helmet",
    nameJa: "ネクロンヘルメット",
    category: "armor",
    templates: ["armor_helm_full", "armor_helm_horn"],
    rarity: "legendary",
    mcItems: ["diamond_helmet"],
    citPattern: "Necron's Helmet",
    lore: "ウィザー王の兜。火力の象徴。",
    tags: ["dungeon", "berserk"],
  },
  {
    id: "necron_chestplate",
    name: "Necron's Chestplate",
    nameJa: "ネクロンチェストプレート",
    category: "armor",
    templates: ["armor_chest_plate", "armor_chest_plate"],
    rarity: "legendary",
    mcItems: ["diamond_chestplate"],
    citPattern: "Necron's Chestplate",
    lore: "黒金の胸当て。",
    tags: ["dungeon", "berserk"],
  },
  {
    id: "necron_leggings",
    name: "Necron's Leggings",
    nameJa: "ネクロンレギンス",
    category: "armor",
    templates: ["armor_legs"],
    rarity: "legendary",
    mcItems: ["diamond_leggings"],
    citPattern: "Necron's Leggings",
    lore: "カタコンブ最深部の守護を纏う。",
    tags: ["dungeon"],
  },
  {
    id: "necron_boots",
    name: "Necron's Boots",
    nameJa: "ネクロンブーツ",
    category: "armor",
    templates: ["armor_boots"],
    rarity: "legendary",
    mcItems: ["diamond_boots"],
    citPattern: "Necron's Boots",
    lore: "王の足音。",
    tags: ["dungeon"],
  },
  {
    id: "storm_helmet",
    name: "Storm's Helmet",
    nameJa: "ストームヘルメット",
    category: "armor",
    templates: ["armor_helm_hood", "armor_helm_full"],
    rarity: "legendary",
    mcItems: ["diamond_helmet"],
    citPattern: "Storm's Helmet",
    lore: "魔力の嵐を閉じ込めた兜。",
    tags: ["dungeon", "mage"],
  },
  {
    id: "storm_chestplate",
    name: "Storm's Chestplate",
    nameJa: "ストームチェストプレート",
    category: "armor",
    templates: ["armor_chest_plate"],
    rarity: "legendary",
    mcItems: ["diamond_chestplate"],
    citPattern: "Storm's Chestplate",
    lore: "雷光を帯びた法衣鎧。",
    tags: ["dungeon", "mage"],
  },
  {
    id: "superior_helmet",
    name: "Superior Dragon Helmet",
    nameJa: "スペリオルドラゴンヘルメット",
    category: "armor",
    templates: ["armor_helm_horn"],
    rarity: "legendary",
    mcItems: ["player_head", "diamond_helmet"],
    citPattern: "Superior Dragon Helmet",
    lore: "最上位竜の頭蓋。",
    tags: ["dragon"],
  },
  {
    id: "superior_chestplate",
    name: "Superior Dragon Chestplate",
    nameJa: "スペリオルドラゴンチェストプレート",
    category: "armor",
    templates: ["armor_chest_plate"],
    rarity: "legendary",
    mcItems: ["diamond_chestplate"],
    citPattern: "Superior Dragon Chestplate",
    lore: "虹色に近い竜鱗。",
    tags: ["dragon"],
  },
  {
    id: "superior_leggings",
    name: "Superior Dragon Leggings",
    nameJa: "スペリオルドラゴンレギンス",
    category: "armor",
    templates: ["armor_legs"],
    rarity: "legendary",
    mcItems: ["diamond_leggings"],
    citPattern: "Superior Dragon Leggings",
    lore: "全てのステータスを底上げする。",
    tags: ["dragon"],
  },
  {
    id: "superior_boots",
    name: "Superior Dragon Boots",
    nameJa: "スペリオルドラゴンブーツ",
    category: "armor",
    templates: ["armor_boots"],
    rarity: "legendary",
    mcItems: ["diamond_boots"],
    citPattern: "Superior Dragon Boots",
    lore: "竜の踵。",
    tags: ["dragon"],
  },
  {
    id: "shadow_assassin_helmet",
    name: "Shadow Assassin Helmet",
    nameJa: "シャドウアサシンヘルメット",
    category: "armor",
    templates: ["armor_helm_hood"],
    rarity: "legendary",
    mcItems: ["player_head", "leather_helmet"],
    citPattern: "Shadow Assassin Helmet",
    lore: "闇に溶ける仮面。",
    tags: ["dungeon", "assassin"],
  },
  {
    id: "shadow_assassin_chestplate",
    name: "Shadow Assassin Chestplate",
    nameJa: "シャドウアサシンチェストプレート",
    category: "armor",
    templates: ["armor_chest_light"],
    rarity: "legendary",
    mcItems: ["leather_chestplate"],
    citPattern: "Shadow Assassin Chestplate",
    lore: "暗殺者の胴衣。",
    tags: ["dungeon", "assassin"],
  },
  {
    id: "shadow_assassin_leggings",
    name: "Shadow Assassin Leggings",
    nameJa: "シャドウアサシンレギンス",
    category: "armor",
    templates: ["armor_legs"],
    rarity: "legendary",
    mcItems: ["leather_leggings"],
    citPattern: "Shadow Assassin Leggings",
    lore: "足音を消す。",
    tags: ["dungeon"],
  },
  {
    id: "shadow_assassin_boots",
    name: "Shadow Assassin Boots",
    nameJa: "シャドウアサシンブーツ",
    category: "armor",
    templates: ["armor_boots"],
    rarity: "legendary",
    mcItems: ["leather_boots"],
    citPattern: "Shadow Assassin Boots",
    lore: "跳躍する影。",
    tags: ["dungeon"],
  },
  {
    id: "crimson_helmet",
    name: "Crimson Helmet",
    nameJa: "クリムゾンヘルメット",
    category: "armor",
    templates: ["armor_helm_full", "armor_helm_horn"],
    rarity: "legendary",
    mcItems: ["player_head", "leather_helmet"],
    citPattern: "Crimson Helmet",
    lore: "真紅の島の覇兜。",
    tags: ["crimson", "kuudra"],
  },
  {
    id: "crimson_chestplate",
    name: "Crimson Chestplate",
    nameJa: "クリムゾンチェストプレート",
    category: "armor",
    templates: ["armor_chest_plate", "armor_chest_plate"],
    rarity: "legendary",
    mcItems: ["leather_chestplate"],
    citPattern: "Crimson Chestplate",
    lore: "溶岩の心拍。",
    tags: ["crimson", "kuudra"],
  },
  {
    id: "aurora_helmet",
    name: "Aurora Helmet",
    nameJa: "オーロラヘルメット",
    category: "armor",
    templates: ["armor_helm_hood"],
    rarity: "legendary",
    mcItems: ["player_head", "leather_helmet"],
    citPattern: "Aurora Helmet",
    lore: "極光を閉じ込めた法帽。",
    tags: ["crimson", "mage"],
  },
  {
    id: "aurora_chestplate",
    name: "Aurora Chestplate",
    nameJa: "オーロラチェストプレート",
    category: "armor",
    templates: ["armor_chest_plate"],
    rarity: "legendary",
    mcItems: ["leather_chestplate"],
    citPattern: "Aurora Chestplate",
    lore: "夜空が鎧になった。",
    tags: ["crimson", "mage"],
  },
  {
    id: "frozen_blaze_helmet",
    name: "Frozen Blaze Helmet",
    nameJa: "フローズンブレイズヘルメット",
    category: "armor",
    templates: ["armor_helm_hood", "armor_helm_full"],
    rarity: "legendary",
    mcItems: ["player_head", "diamond_helmet"],
    citPattern: "Frozen Blaze Helmet",
    lore: "凍てついた炎の冠。",
    tags: ["blaze", "ice"],
  },
  {
    id: "frozen_blaze_chestplate",
    name: "Frozen Blaze Chestplate",
    nameJa: "フローズンブレイズチェストプレート",
    category: "armor",
    templates: ["armor_chest_plate"],
    rarity: "legendary",
    mcItems: ["diamond_chestplate"],
    citPattern: "Frozen Blaze Chestplate",
    lore: "冷炎の炉心。",
    tags: ["blaze", "ice"],
  },
  {
    id: "stonk",
    name: "Stonk",
    nameJa: "ストック",
    category: "tool",
    templates: ["tool_pickaxe"],
    rarity: "epic",
    mcItems: ["golden_pickaxe", "diamond_pickaxe"],
    citPattern: "Stonk",
    lore: "効率と経験値の黄金ツルハシ。",
    tags: ["mining", "dungeon"],
  },
  {
    id: "treecapitator",
    name: "Treecapitator",
    nameJa: "ツリーキャピテイター",
    category: "tool",
    templates: ["tool_axe"],
    rarity: "epic",
    mcItems: ["golden_axe", "diamond_axe"],
    citPattern: "Treecapitator",
    lore: "一本の振りで森が倒れる。",
    tags: ["foraging"],
  },
  {
    id: "titanium_drill",
    name: "Titanium Drill DR-X655",
    nameJa: "チタニウムドリル",
    category: "tool",
    templates: ["tool_drill"],
    rarity: "legendary",
    mcItems: ["prismarine_shard", "diamond_pickaxe"],
    citPattern: "Titanium Drill",
    lore: "ドワーフ鉱山の最上級穿孔機。",
    tags: ["mining"],
  },
  {
    id: "gemstone_gauntlet",
    name: "Gemstone Gauntlet",
    nameJa: "ジェムストーンガントレット",
    category: "tool",
    templates: ["tool_gauntlet"],
    rarity: "legendary",
    mcItems: ["player_head"],
    citPattern: "Gemstone Gauntlet",
    lore: "宝石を嵌めた採掘拳。",
    tags: ["mining", "crystal"],
  },
  {
    id: "grappling_hook",
    name: "Grappling Hook",
    nameJa: "グラップリングフック",
    category: "tool",
    templates: ["tool_hook", "tool_rod"],
    rarity: "uncommon",
    mcItems: ["fishing_rod"],
    citPattern: "Grappling Hook",
    lore: "フックで宙を泳ぐ。",
    tags: ["utility"],
  },
  {
    id: "rod_of_the_sea",
    name: "Rod of the Sea",
    nameJa: "ロッド・オブ・ザ・シー",
    category: "tool",
    templates: ["tool_rod"],
    rarity: "legendary",
    mcItems: ["fishing_rod"],
    citPattern: "Rod of the Sea",
    lore: "海そのものを釣る竿。",
    tags: ["fishing"],
  },
  {
    id: "mathematical_hoe",
    name: "Mathematical Hoe Blueprint",
    nameJa: "マスマティカルクワ",
    category: "tool",
    templates: ["tool_hoe"],
    rarity: "legendary",
    mcItems: ["diamond_hoe", "golden_hoe"],
    citPattern: "Mathematical Hoe",
    lore: "収穫を数式にする。",
    tags: ["farming"],
  },
  {
    id: "hegemony_artifact",
    name: "Hegemony Artifact",
    nameJa: "ヘゲモニーアーティファクト",
    category: "accessory",
    templates: ["acc_artifact"],
    rarity: "legendary",
    mcItems: ["player_head"],
    citPattern: "Hegemony Artifact",
    lore: "力の覇権を示す遺物。",
    tags: ["accessory", "mp"],
  },
  {
    id: "overflux_capacitor",
    name: "Overflux Power Orb",
    nameJa: "オーバーフラックス",
    category: "accessory",
    templates: ["acc_artifact", "acc_crystal"],
    rarity: "epic",
    mcItems: ["player_head"],
    citPattern: "Overflux",
    lore: "赤い力のオーブ。",
    tags: ["orb"],
  },
  {
    id: "plasmaflux",
    name: "Plasmaflux Power Orb",
    nameJa: "プラズマフラックス",
    category: "accessory",
    templates: ["acc_artifact", "acc_crystal"],
    rarity: "legendary",
    mcItems: ["player_head"],
    citPattern: "Plasmaflux",
    lore: "紫電のオーブ。",
    tags: ["orb"],
  },
  {
    id: "relic_of_power",
    name: "Relic of Power",
    nameJa: "レリック・オブ・パワー",
    category: "accessory",
    templates: ["acc_talisman", "acc_artifact"],
    rarity: "epic",
    mcItems: ["player_head"],
    citPattern: "Relic of Power",
    lore: "魔力を底上げする遺物。",
    tags: ["accessory"],
  },
  {
    id: "speed_talisman",
    name: "Speed Talisman",
    nameJa: "スピードタリスマン",
    category: "accessory",
    templates: ["acc_talisman"],
    rarity: "common",
    mcItems: ["player_head"],
    citPattern: "Speed Talisman",
    lore: "最初の加速のお守り。",
    tags: ["accessory", "early"],
  },
  {
    id: "treasure_ring",
    name: "Treasure Ring",
    nameJa: "トレジャーリング",
    category: "accessory",
    templates: ["acc_ring"],
    rarity: "epic",
    mcItems: ["player_head"],
    citPattern: "Treasure Ring",
    lore: "宝を呼び寄せる指輪。",
    tags: ["accessory", "fishing"],
  },
  {
    id: "personal_compactor",
    name: "Personal Compactor 7000",
    nameJa: "パーソナルコンパクター",
    category: "accessory",
    templates: ["acc_artifact"],
    rarity: "legendary",
    mcItems: ["player_head", "dropper"],
    citPattern: "Personal Compactor",
    lore: "インベントリを圧縮する機械。",
    tags: ["utility"],
  },
  {
    id: "golden_dragon_pet",
    name: "Golden Dragon",
    nameJa: "ゴールデンドラゴン",
    category: "pet",
    templates: ["pet_dragon"],
    rarity: "legendary",
    mcItems: ["player_head"],
    citPattern: "Golden Dragon",
    lore: "金貨を産む伝説の仔竜。",
    tags: ["pet", "gold"],
  },
  {
    id: "blue_whale_pet",
    name: "Blue Whale",
    nameJa: "ブルーホエール",
    category: "pet",
    templates: ["pet_whale"],
    rarity: "legendary",
    mcItems: ["player_head"],
    citPattern: "Blue Whale",
    lore: "HPの海。",
    tags: ["pet", "tank"],
  },
  {
    id: "tiger_pet",
    name: "Tiger",
    nameJa: "タイガー",
    category: "pet",
    templates: ["pet_quadruped"],
    rarity: "legendary",
    mcItems: ["player_head"],
    citPattern: "Tiger",
    lore: "クリティカルの獣。",
    tags: ["pet", "crit"],
  },
  {
    id: "black_cat_pet",
    name: "Black Cat",
    nameJa: "ブラックキャット",
    category: "pet",
    templates: ["pet_quadruped"],
    rarity: "legendary",
    mcItems: ["player_head"],
    citPattern: "Black Cat",
    lore: "速度と魔法発見の黒猫。",
    tags: ["pet", "magic_find"],
  },
  {
    id: "griffin_pet",
    name: "Griffin",
    nameJa: "グリフィン",
    category: "pet",
    templates: ["pet_bird", "pet_dragon"],
    rarity: "legendary",
    mcItems: ["player_head"],
    citPattern: "Griffin",
    lore: "神話狩りを導く聖獣。",
    tags: ["pet", "mythological"],
  },
  {
    id: "bee_pet",
    name: "Bee",
    nameJa: "ビー",
    category: "pet",
    templates: ["pet_bee"],
    rarity: "legendary",
    mcItems: ["player_head"],
    citPattern: "Bee",
    lore: "花粉と知能の相棒。",
    tags: ["pet", "farming"],
  },
  {
    id: "phoenix_pet",
    name: "Phoenix",
    nameJa: "フェニックス",
    category: "pet",
    templates: ["pet_bird", "pet_dragon"],
    rarity: "legendary",
    mcItems: ["player_head"],
    citPattern: "Phoenix",
    lore: "灰から蘇る火力。",
    tags: ["pet", "mage"],
  },
  {
    id: "enderman_pet",
    name: "Enderman",
    nameJa: "エンダーマン",
    category: "pet",
    templates: ["pet_quadruped", "minion_base"],
    rarity: "legendary",
    mcItems: ["player_head"],
    citPattern: "Enderman",
    lore: "虚空の視線。",
    tags: ["pet", "end"],
  },
  {
    id: "inferno_minion",
    name: "Inferno Minion",
    nameJa: "インフェルノミニオン",
    category: "minion",
    templates: ["minion_base"],
    rarity: "legendary",
    mcItems: ["player_head"],
    citPattern: "Inferno Minion",
    lore: "地獄の自動装置。",
    tags: ["minion", "crimson"],
  },
  {
    id: "vampire_minion",
    name: "Vampire Minion",
    nameJa: "ヴァンパイアミニオン",
    category: "minion",
    templates: ["minion_base"],
    rarity: "rare",
    mcItems: ["player_head"],
    citPattern: "Vampire Minion",
    lore: "血を滴らせる作業員。",
    tags: ["minion", "rift"],
  },
  {
    id: "snow_minion",
    name: "Snow Minion",
    nameJa: "スノーミニオン",
    category: "minion",
    templates: ["minion_base"],
    rarity: "rare",
    mcItems: ["player_head"],
    citPattern: "Snow Minion",
    lore: "雪を積み続ける。",
    tags: ["minion", "event"],
  },
  {
    id: "clay_minion",
    name: "Clay Minion",
    nameJa: "クレイミニオン",
    category: "minion",
    templates: ["minion_base"],
    rarity: "rare",
    mcItems: ["player_head"],
    citPattern: "Clay Minion",
    lore: "初期の相棒。粘土を掘る。",
    tags: ["minion", "early"],
  },
  {
    id: "enchanted_book",
    name: "Enchanted Book",
    nameJa: "エンチャント本",
    category: "misc",
    templates: ["acc_book"],
    rarity: "uncommon",
    mcItems: ["enchanted_book"],
    citPattern: "Enchanted Book",
    lore: "未知のルーンが走る冊子。",
    tags: ["enchanting"],
  },
  {
    id: "critical_potion",
    name: "Critical Potion",
    nameJa: "クリティカルポーション",
    category: "misc",
    templates: ["acc_potion"],
    rarity: "rare",
    mcItems: ["potion"],
    citPattern: "Critical I",
    lore: "会心を煮詰めた瓶。",
    tags: ["alchemy"],
  },
  {
    id: "gemstone_mixture",
    name: "Gemstone Mixture",
    nameJa: "ジェムストーンミックス",
    category: "misc",
    templates: ["acc_crystal"],
    rarity: "rare",
    mcItems: ["player_head", "prismarine_crystals"],
    citPattern: "Gemstone Mixture",
    lore: "宝石を溶かし合わせた塊。",
    tags: ["mining", "crystal"],
  },
  {
    id: "wither_shield_scroll",
    name: "Wither Shield",
    nameJa: "ウィザーシールド",
    category: "misc",
    templates: ["acc_book", "acc_artifact"],
    rarity: "epic",
    mcItems: ["paper", "enchanted_book"],
    citPattern: "Wither Shield",
    lore: "ブレイドに載せる防御スクロール。",
    tags: ["dungeon", "scroll"],
  },
  {
    id: "implosion_scroll",
    name: "Implosion",
    nameJa: "インプロージョン",
    category: "misc",
    templates: ["acc_book", "acc_crystal"],
    rarity: "epic",
    mcItems: ["paper", "enchanted_book"],
    citPattern: "Implosion",
    lore: "一点に世界を折り畳む。",
    tags: ["dungeon", "scroll"],
  },
  {
    id: "gyrokinetic_wand",
    name: "Gyrokinetic Wand",
    nameJa: "ジャイロキネティックワンド",
    category: "staff",
    templates: ["staff_gyro", "staff_sceptre"],
    rarity: "epic",
    mcItems: ["blaze_rod", "stick"],
    citPattern: "Gyrokinetic Wand",
    lore: "物理法則を歪めて周囲の敵を回転吸引する時計仕掛けのジャイロ杖。",
    tags: ["mechanical", "clockwork", "utility", "mage"],
  },
  {
    id: "hyper_cleaver",
    name: "Hyper Cleaver",
    nameJa: "ハイパークリーバー",
    category: "sword",
    templates: ["sword_chainsaw", "sword_great"],
    rarity: "rare",
    mcItems: ["golden_sword", "iron_sword"],
    citPattern: "Hyper Cleaver",
    lore: "超高速回転する連鎖刃を備えた重装兵用大型機械大鉈。",
    tags: ["mechanical", "cleaver", "dungeon", "berserk"],
  },
  {
    id: "plasma_chainsaw",
    name: "Plasma Chainsaw",
    nameJa: "プラズマチェーンソー",
    category: "sword",
    templates: ["sword_chainsaw", "sword_piston"],
    rarity: "legendary",
    mcItems: ["diamond_axe", "diamond_sword"],
    citPattern: "Plasma Chainsaw",
    lore: "超高熱プラズマを帯びた高速回転歯車で装甲を焼き切る工業伐採機。",
    tags: ["mechanical", "cyber", "plasma", "industrial"],
  },
  {
    id: "steampunk_railgun",
    name: "Dwarven Railgun",
    nameJa: "ドワーフ・レールガン",
    category: "bow",
    templates: ["bow_railgun", "bow_heavy"],
    rarity: "legendary",
    mcItems: ["bow", "crossbow"],
    citPattern: "Dwarven Railgun",
    lore: "電磁レールコイルで鉄杭を音速射出するドワーフ超兵器。",
    tags: ["mechanical", "dwarf", "railgun", "archer"],
  },
  {
    id: "flintlock_repeater",
    name: "Clockwork Repeater",
    nameJa: "クロックワーク・リピーター",
    category: "bow",
    templates: ["bow_crossbow", "bow_railgun"],
    rarity: "epic",
    mcItems: ["crossbow", "bow"],
    citPattern: "Clockwork Repeater",
    lore: "精密歯車の連動により矢を高速装填して連射する機械弓銃。",
    tags: ["mechanical", "clockwork", "steampunk", "archer"],
  },
  {
    id: "steam_pilebunker",
    name: "Hydraulic Pilebunker",
    nameJa: "油圧パイルバンカー",
    category: "tool",
    templates: ["tool_pilebunker", "tool_gauntlet"],
    rarity: "legendary",
    mcItems: ["diamond_pickaxe", "iron_pickaxe"],
    citPattern: "Hydraulic Pilebunker",
    lore: "超高圧蒸気シリンダーで超硬質杭を射ち込み岩盤を粉砕する腕部兵器。",
    tags: ["mechanical", "steam", "mining", "heavy"],
  },
  {
    id: "artificer_wrench",
    name: "Artificer's Omni-Wrench",
    nameJa: "アーティフィサーズ・レンチ",
    category: "tool",
    templates: ["tool_wrench", "tool_drill"],
    rarity: "rare",
    mcItems: ["iron_pickaxe", "shears"],
    citPattern: "Artificer's Omni-Wrench",
    lore: "あらゆる機械構造を瞬時に調整・分解できる工房の万能変形レンチ。",
    tags: ["mechanical", "steampunk", "tool", "utility"],
  },
  {
    id: "automaton_blade",
    name: "Automaton Heartblade",
    nameJa: "オートマタ・ハートブレード",
    category: "sword",
    templates: ["sword_piston", "sword_broad"],
    rarity: "legendary",
    mcItems: ["diamond_sword", "iron_sword"],
    citPattern: "Automaton Heartblade",
    lore: "古代オートマタの永久機関コアを組み込み、蒸気圧で斬撃を加速する機械剣。",
    tags: ["mechanical", "automaton", "steampunk", "berserk"],
  },
  {
    id: "tachyon_cleaver",
    name: "Tachyon Cleaver",
    nameJa: "タキオンクリーバー",
    category: "sword",
    templates: ["sword_chainsaw", "sword_katana"],
    rarity: "legendary",
    mcItems: ["diamond_sword"],
    citPattern: "Tachyon Cleaver",
    lore: "時間加速ピストンと電磁ブレードにより振りの瞬間だけ加速する超未来大鉈。",
    tags: ["mechanical", "cyber", "tachyon", "crit"],
  },
  {
    id: "mecha_gauntlet",
    name: "Steamwork Power Gauntlet",
    nameJa: "スチームワーク・パワーガントレット",
    category: "tool",
    templates: ["tool_pilebunker", "tool_gauntlet"],
    rarity: "epic",
    mcItems: ["player_head", "golden_pickaxe"],
    citPattern: "Steamwork Power Gauntlet",
    lore: "真鍮歯車と排気バルブを搭載し、打撃と採掘を同時に強化する強化手甲。",
    tags: ["mechanical", "steampunk", "brass", "mining"],
  },
];

export const CATALOG_MAP: Record<string, CatalogItem> = Object.fromEntries(
  CATALOG.map((item) => [item.id, item]),
);

export function getItem(id: string): CatalogItem | undefined {
  return CATALOG_MAP[id];
}

export function itemsByCategory(category: Category | "all"): CatalogItem[] {
  if (category === "all") return CATALOG;
  return CATALOG.filter((item) => item.category === category);
}

export function searchItems(query: string): CatalogItem[] {
  const q = query.trim().toLowerCase();
  if (!q) return CATALOG;
  return CATALOG.filter((item) => {
    const hay = `${item.name} ${item.nameJa} ${item.id} ${item.tags.join(" ")} ${item.lore}`.toLowerCase();
    return hay.includes(q);
  });
}
