import { ARCHES, type ArchId, type Design, type Adornment } from './forge-archetypes';
import type { GradSpec } from './forge-gradient';
import type { Mats, Anim } from './forge-engine';

import type { CatItem, RarityId } from './forge-catalog';

export type ForgeTheme = {
  id: string;
  name: string;
  enPrefix: string;
  jpPrefix: string;
  rarity: RarityId;
  anim: Anim;
  mats: Mats;
  preferredArches: ArchId[];
  ornBias: number;
  gemBias: boolean;
  runeBias: boolean;
  adornment: Adornment;
  /** gradient the theme stamps onto generated items (item-level override) */
  grad?: GradSpec;
};

export const THEMES: ForgeTheme[] = [
  {
    id: 'celestial',
    name: '天星 / Celestial',
    enPrefix: 'Celestial',
    jpPrefix: '天星の',
    rarity: 'divine',
    anim: 'aurora',
    mats: { main: 'mithril', trim: 'gold', grip: 'silk', gem: 'sapphire', aura: 'spirit' },
    preferredArches: ['sword', 'shield', 'staff', 'star', 'wand', 'orb', 'book'],
    ornBias: 0.85,
    gemBias: true,
    runeBias: true,
    adornment: 'orbitals',
  },
  {
    id: 'dragon_crimson',
    name: '竜焔 / Dragonflame',
    enPrefix: 'Dragonflame',
    jpPrefix: '竜焔の',
    rarity: 'legendary',
    anim: 'flame',
    mats: { main: 'crimson', trim: 'gold', grip: 'leather', gem: 'ruby', aura: 'flame' },
    preferredArches: ['sword', 'axe', 'scythe', 'helmet', 'chest', 'shield'],
    ornBias: 0.9,
    gemBias: true,
    runeBias: true,
    adornment: 'crest',
  },
  {
    id: 'void_stalker',
    name: '虚空 / Void Stalker',
    enPrefix: 'Voidborn',
    jpPrefix: '虚空の',
    rarity: 'mythic',
    anim: 'pulse',
    mats: { main: 'obsidian', trim: 'blackgold', grip: 'wither', gem: 'amethyst', aura: 'void' },
    preferredArches: ['scythe', 'dagger', 'sword', 'bow', 'orb', 'legs'],
    ornBias: 0.65,
    gemBias: false,
    runeBias: true,
    adornment: 'sigil',
  },
  {
    id: 'frost_wyrm',
    name: '霜晶 / Frost Wyrm',
    enPrefix: 'Glacial',
    jpPrefix: '氷華の',
    rarity: 'epic',
    anim: 'frost',
    mats: { main: 'frost', trim: 'steel', grip: 'silk', gem: 'diamond', aura: 'spirit' },
    preferredArches: ['sword', 'dagger', 'bow', 'wand', 'gem', 'boots'],
    ornBias: 0.6,
    gemBias: true,
    runeBias: false,
    adornment: 'petals',
  },
  {
    id: 'midas_sovereign',
    name: '帝王 / Midas Sovereign',
    enPrefix: 'Sovereign',
    jpPrefix: '黄金の',
    rarity: 'legendary',
    anim: 'twinkle',
    mats: { main: 'gold', trim: 'gold', grip: 'crimson', gem: 'amber', aura: 'flame' },
    preferredArches: ['sword', 'staff', 'shield', 'coin', 'ingot', 'helmet'],
    ornBias: 0.95,
    gemBias: true,
    runeBias: false,
    adornment: 'filigree',
  },
  {
    id: 'toxic_abyss',
    name: '猛毒 / Venomous',
    enPrefix: 'Venomous',
    jpPrefix: '猛毒の',
    rarity: 'epic',
    anim: 'flow',
    mats: { main: 'netherite', trim: 'emerald', grip: 'ebony', gem: 'emerald', aura: 'toxic' },
    preferredArches: ['dagger', 'scythe', 'axe', 'potion', 'drill', 'rod'],
    ornBias: 0.5,
    gemBias: true,
    runeBias: true,
    adornment: 'thorns',
  },
  {
    id: 'storm_caller',
    name: '雷光 / Stormcaller',
    enPrefix: 'Storm',
    jpPrefix: '雷霆の',
    rarity: 'legendary',
    anim: 'lightning',
    mats: { main: 'titanium', trim: 'mithril', grip: 'leather', gem: 'sapphire', aura: 'storm' },
    preferredArches: ['axe', 'pickaxe', 'sword', 'staff', 'shield'],
    ornBias: 0.75,
    gemBias: true,
    runeBias: true,
    adornment: 'sigil',
  },
  {
    id: 'arcane_scholar',
    name: '秘術 / Arcane',
    enPrefix: 'Arcane',
    jpPrefix: '秘術の',
    rarity: 'epic',
    anim: 'arcane',
    mats: { main: 'ebony', trim: 'amethyst', grip: 'silk', gem: 'amethyst', aura: 'void' },
    preferredArches: ['book', 'staff', 'wand', 'orb', 'gem'],
    ornBias: 0.8,
    gemBias: true,
    runeBias: true,
    adornment: 'orbitals',
  },
  {
    id: 'holy_paladin',
    name: '聖騎士 / Paladin',
    enPrefix: 'Radiant',
    jpPrefix: '聖光の',
    rarity: 'mythic',
    anim: 'shimmer',
    mats: { main: 'steel', trim: 'gold', grip: 'leather', gem: 'diamond', aura: 'spirit' },
    preferredArches: ['sword', 'shield', 'helmet', 'chest', 'legs', 'boots'],
    ornBias: 0.85,
    gemBias: true,
    runeBias: false,
    adornment: 'crest',
  },
  {
    id: 'underworld_wither',
    name: '冥界 / Nether Wither',
    enPrefix: 'Withered',
    jpPrefix: '凋落の',
    rarity: 'mythic',
    anim: 'embers',
    mats: { main: 'wither', trim: 'blackgold', grip: 'bone', gem: 'ruby', aura: 'blood' },
    preferredArches: ['scythe', 'sword', 'axe', 'helmet', 'shield', 'potion'],
    ornBias: 0.7,
    gemBias: false,
    runeBias: true,
    adornment: 'thorns',
  },
  {
    id: 'divan_gilded',
    name: '金彩 / Divan Gilded',
    enPrefix: "Divan's",
    jpPrefix: '金彩の',
    rarity: 'mythic',
    anim: 'shimmer',
    mats: { main: 'rosegold', trim: 'gold', grip: 'leather', gem: 'opal', aura: 'spirit' },
    preferredArches: ['drill', 'pickaxe', 'axe', 'helmet', 'chest', 'legs', 'boots'],
    ornBias: 0.9,
    gemBias: true,
    runeBias: false,
    adornment: 'filigree',
  },
  {
    id: 'jade_crystal',
    name: '翡翠 / Jade Crystal',
    enPrefix: 'Crystal',
    jpPrefix: '翡翠の',
    rarity: 'legendary',
    anim: 'twinkle',
    mats: { main: 'jade', trim: 'copper', grip: 'silk', gem: 'emerald', aura: 'toxic' },
    preferredArches: ['gem', 'wand', 'staff', 'orb', 'dagger', 'helmet'],
    ornBias: 0.7,
    gemBias: true,
    runeBias: true,
    adornment: 'petals',
  },
  {
    id: 'mechanized',
    name: '機械 / Mechanized',
    enPrefix: 'Mechanized',
    jpPrefix: '機械仕掛けの',
    rarity: 'epic',
    anim: 'orbit',
    mats: { main: 'gunmetal', trim: 'copper', grip: 'leather', gem: 'amber', aura: 'storm' },
    preferredArches: ['chainsaw', 'drill', 'railgun', 'gun', 'pickaxe', 'crossbow', 'mace'],
    ornBias: 0.45,
    gemBias: true,
    runeBias: false,
    adornment: 'none',
  },
  {
    id: 'modern_tactical',
    name: '近代 / Tactical',
    enPrefix: 'Tactical',
    jpPrefix: '近代の',
    rarity: 'rare',
    anim: 'none',
    mats: { main: 'carbon', trim: 'gunmetal', grip: 'leather', gem: 'neon', aura: 'neon' },
    preferredArches: ['gun', 'crossbow', 'railgun', 'chainsaw', 'dagger', 'helmet'],
    ornBias: 0.2,
    gemBias: false,
    runeBias: false,
    adornment: 'none',
  },
  {
    id: 'chrome_railgun',
    name: '超電磁 / Hypercoil',
    enPrefix: 'Hypercoil',
    jpPrefix: '超電磁の',
    rarity: 'divine',
    anim: 'lightning',
    mats: { main: 'chrome', trim: 'titanium', grip: 'carbon', gem: 'frost', aura: 'plasma' },
    preferredArches: ['railgun', 'gun', 'staff', 'wand', 'spear', 'shield'],
    ornBias: 0.5,
    gemBias: true,
    runeBias: true,
    adornment: 'orbitals',
  },
  {
    id: 'eldritch_cursed',
    name: '禍々 / Eldritch',
    enPrefix: 'Eldritch',
    jpPrefix: '禍々しき',
    rarity: 'mythic',
    anim: 'pulse',
    mats: { main: 'chitin', trim: 'bone', grip: 'sinew', gem: 'void', aura: 'void' },
    preferredArches: ['grimblade', 'scythe', 'spear', 'mace', 'staff', 'orb', 'helmet'],
    ornBias: 0.95,
    gemBias: true,
    runeBias: true,
    adornment: 'thorns',
  },
  {
    id: 'bloodforged',
    name: '血統 / Bloodforged',
    enPrefix: 'Bloodforged',
    jpPrefix: '血統の',
    rarity: 'legendary',
    anim: 'flow',
    mats: { main: 'rust', trim: 'blackgold', grip: 'gore', gem: 'ruby', aura: 'blood' },
    preferredArches: ['grimblade', 'scythe', 'mace', 'spear', 'dagger', 'chainsaw'],
    ornBias: 0.8,
    gemBias: true,
    runeBias: true,
    adornment: 'sigil',
  },
  {
    id: 'spear_regalia',
    name: '儀仗 / Regalia',
    enPrefix: 'Regal',
    jpPrefix: '儀仗の',
    rarity: 'mythic',
    anim: 'shimmer',
    mats: { main: 'gold', trim: 'rosegold', grip: 'silk', gem: 'opal', aura: 'spirit' },
    preferredArches: ['spear', 'mace', 'shield', 'staff', 'crossbow', 'helmet'],
    ornBias: 1,
    gemBias: true,
    runeBias: true,
    adornment: 'filigree',
  },
  {
    id: 'tidal_prismarine',
    name: '潮流 / Tidal',
    enPrefix: 'Tidal',
    jpPrefix: '潮流の',
    rarity: 'epic',
    anim: 'water',
    mats: { main: 'prismarine', trim: 'copper', grip: 'leather', gem: 'diamond', aura: 'spirit' },
    preferredArches: ['rod', 'staff', 'shield', 'chest', 'orb', 'sword'],
    ornBias: 0.6,
    gemBias: true,
    runeBias: false,
    adornment: 'orbitals',
  },
  {
    id: 'grimoire_arcana',
    name: '魔導書 / Grimoire',
    enPrefix: 'Grimoire',
    jpPrefix: '魔導の',
    rarity: 'epic',
    anim: 'enchant',
    mats: { main: 'ebony', trim: 'amethyst', grip: 'silk', gem: 'amethyst', aura: 'spirit' },
    preferredArches: ['tome', 'book', 'staff', 'wand', 'orb'],
    ornBias: 0.9,
    gemBias: true,
    runeBias: true,
    adornment: 'sigil',
    grad: { mode: 'radial', angle: 135, bias: 0, contrast: 0.9, spread: 0.55, local: true },
  },
  {
    id: 'ancient_relic',
    name: '古代遺物 / Ancient Relic',
    enPrefix: 'Ancient',
    jpPrefix: '古代の',
    rarity: 'mythic',
    anim: 'arcane',
    mats: { main: 'blackgold', trim: 'gold', grip: 'bone', gem: 'opal', aura: 'spirit' },
    preferredArches: ['relic', 'tome', 'mace', 'spear', 'shield', 'orb'],
    ornBias: 1,
    gemBias: true,
    runeBias: true,
    adornment: 'orbitals',
    grad: { mode: 'vignette', angle: 135, bias: 0.05, contrast: 1.1, spread: 0.5, local: true },
  },
  {
    id: 'cursed_grim',
    name: '禍々 / Grim Curse',
    enPrefix: 'Grim',
    jpPrefix: '禍々しき',
    rarity: 'mythic',
    anim: 'smoke',
    mats: { main: 'chitin', trim: 'bone', grip: 'sinew', gem: 'toxic', aura: 'toxic' },
    preferredArches: ['grimblade', 'scythe', 'relic', 'tome', 'mace', 'spear'],
    ornBias: 0.95,
    gemBias: true,
    runeBias: true,
    adornment: 'thorns',
    grad: { mode: 'split', angle: 115, bias: 0, contrast: 1.3, spread: 0.4, local: true },
  },
  {
    id: 'blood_rite',
    name: '血の儀式 / Blood Rite',
    enPrefix: 'Blood',
    jpPrefix: '血の',
    rarity: 'legendary',
    anim: 'drip',
    mats: { main: 'rust', trim: 'blackgold', grip: 'gore', gem: 'ruby', aura: 'blood' },
    preferredArches: ['grimblade', 'scythe', 'tome', 'relic', 'dagger', 'spear', 'mace'],
    ornBias: 0.85,
    gemBias: true,
    runeBias: true,
    adornment: 'sigil',
    grad: { mode: 'diagonal', angle: 135, bias: -0.1, contrast: 1.15, spread: 0.5, local: true },
  },
  {
    id: 'machine_core',
    name: '機械核 / Machine Core',
    enPrefix: 'Machined',
    jpPrefix: '機械の',
    rarity: 'epic',
    anim: 'charge',
    mats: { main: 'gunmetal', trim: 'copper', grip: 'carbon', gem: 'amber', aura: 'neon' },
    preferredArches: ['chainsaw', 'gun', 'railgun', 'drill', 'crossbow', 'relic'],
    ornBias: 0.5,
    gemBias: true,
    runeBias: false,
    adornment: 'orbitals',
    grad: { mode: 'band', angle: 90, bias: 0, contrast: 1, spread: 0.28, local: true },
  },
  {
    id: 'spellcircle',
    name: '魔法陣 / Spell Circle',
    enPrefix: 'Runic',
    jpPrefix: '魔導の',
    rarity: 'divine',
    anim: 'shockwave',
    mats: { main: 'mithril', trim: 'gold', grip: 'silk', gem: 'sapphire', aura: 'plasma' },
    preferredArches: ['tome', 'relic', 'staff', 'wand', 'orb', 'shield'],
    ornBias: 1,
    gemBias: true,
    runeBias: true,
    adornment: 'sigil',
    grad: { mode: 'ripple', angle: 135, bias: 0, contrast: 1.1, spread: 0.45, local: true },
  },
];

const rnd = Math.random;
const pickOne = <T,>(arr: readonly T[]): T => arr[Math.floor(rnd() * arr.length)];

const DEFAULT_BASES: Record<ArchId, string> = {
  sword: 'iron_sword', dagger: 'iron_sword', scythe: 'diamond_hoe', axe: 'diamond_axe', pickaxe: 'diamond_pickaxe', drill: 'prismarine_shard',
  bow: 'bow', staff: 'blaze_rod', wand: 'stick', rod: 'fishing_rod', helmet: 'diamond_helmet', chest: 'leather_chestplate',
  legs: 'leather_leggings', boots: 'leather_boots', shield: 'shield', book: 'book', gem: 'diamond', orb: 'ender_pearl', star: 'nether_star',
  ingot: 'gold_ingot', coin: 'gold_ingot', potion: 'book',
  // modern / mechanical pieces have no 1.8.9 equivalent; they ride on handheld
  // proxies so the legacy CIT target still shows the art
  chainsaw: 'diamond_axe', gun: 'iron_hoe', railgun: 'diamond_hoe',
  spear: 'iron_shovel', mace: 'iron_axe', crossbow: 'bow',
  runeblade: 'diamond_sword', grimblade: 'iron_sword',
  tome: 'book', relic: 'nether_star',
};

export function createThemedItem(themeOrId?: string | ForgeTheme, preferredArch?: ArchId): CatItem {
  const theme = typeof themeOrId === 'object'
    ? themeOrId
    : THEMES.find((t) => t.id === themeOrId) ?? pickOne(THEMES);
  const arch: ArchId = preferredArch ?? pickOne(theme.preferredArches.length ? theme.preferredArches : (Object.keys(ARCHES) as ArchId[]));
  const A = ARCHES[arch];
  const design: Design = {
    arch,
    a: Math.floor(rnd() * A.A.length),
    b: Math.floor(rnd() * A.B.length),
    len: 0.45 + rnd() * 0.5,
    wid: 0.45 + rnd() * 0.45,
    orn: theme.ornBias * (0.6 + rnd() * 0.4),
    gem: rnd() < (theme.gemBias ? 0.85 : 0.35),
    rune: rnd() < (theme.runeBias ? 0.8 : 0.3),
    coreMode: Math.floor(rnd() * 4),
    offsetX: 0,
    offsetY: 0,
    scaleX: 1,
    scaleY: 1,
    rotation: 0,
    flipX: false,
    flipY: false,
    autoFit: true,
    adornment: theme.adornment,
    grad: theme.grad,
  };

  const id = `${theme.id.toUpperCase()}_${arch.toUpperCase()}_${Math.floor(rnd() * 899 + 100)}`;
  const en = `${theme.enPrefix} ${A.en}`;
  const jp = `${theme.jpPrefix}${A.jp}`;

  return {
    id,
    en,
    jp,
    base: DEFAULT_BASES[arch],
    rarity: theme.rarity,
    type: arch === 'shield' ? 'SHIELD' : A.cat === '武器' ? 'WEAPON' : A.cat === '防具' ? 'ARMOR' : undefined,
    design,
    mats: { ...theme.mats },
    anim: theme.anim,
  };
}
