import { CLASS_MAP } from "../mod/codegenMojmap";

/** Minecraft 1.21.11 (Mojang 公式マッピング) のクラス辞書。実 jar と機械照合済み (scripts: verify-registry) */
export const MOJ_MINECRAFT_FQNS: string[] = [
  "com.mojang.blaze3d.platform.InputConstants",
  "net.minecraft.ChatFormatting",
  "net.minecraft.client.DeltaTracker",
  "net.minecraft.client.KeyMapping",
  "net.minecraft.client.Minecraft",
  "net.minecraft.client.gui.Font",
  "net.minecraft.client.gui.GuiGraphics",
  "net.minecraft.client.player.LocalPlayer",
  "net.minecraft.commands.CommandBuildContext",
  "net.minecraft.commands.CommandSourceStack",
  "net.minecraft.commands.Commands",
  "net.minecraft.commands.SharedSuggestionProvider",
  "net.minecraft.core.BlockPos",
  "net.minecraft.core.Direction",
  "net.minecraft.core.Holder",
  "net.minecraft.core.Registry",
  "net.minecraft.core.component.DataComponents",
  "net.minecraft.core.particles.ParticleOptions",
  "net.minecraft.core.particles.ParticleTypes",
  "net.minecraft.core.particles.SimpleParticleType",
  "net.minecraft.core.registries.BuiltInRegistries",
  "net.minecraft.core.registries.Registries",
  "net.minecraft.network.RegistryFriendlyByteBuf",
  "net.minecraft.network.chat.Component",
  "net.minecraft.network.chat.MutableComponent",
  "net.minecraft.network.codec.ByteBufCodecs",
  "net.minecraft.network.codec.StreamCodec",
  "net.minecraft.network.protocol.common.custom.CustomPacketPayload",
  "net.minecraft.network.protocol.game.ClientboundSetSubtitleTextPacket",
  "net.minecraft.network.protocol.game.ClientboundSetTitleTextPacket",
  "net.minecraft.network.protocol.game.ClientboundSetTitlesAnimationPacket",
  "net.minecraft.resources.Identifier",
  "net.minecraft.resources.ResourceKey",
  "net.minecraft.world.BossEvent",
  "net.minecraft.server.bossevents.CustomBossEvent",
  "net.minecraft.server.bossevents.CustomBossEvents",
  "net.minecraft.world.scores.Scoreboard",
  "net.minecraft.world.scores.ServerScoreboard",
  "net.minecraft.world.scores.Objective",
  "net.minecraft.world.scores.ScoreAccess",
  "net.minecraft.world.scores.ScoreHolder",
  "net.minecraft.world.scores.criteria.ObjectiveCriteria",
  "net.minecraft.network.protocol.game.ClientboundEntityEventPacket",
  "net.minecraft.world.SimpleMenuProvider",
  "net.minecraft.world.SimpleContainer",
  "net.minecraft.world.Container",
  "net.minecraft.world.MenuProvider",
  "net.minecraft.world.entity.player.Inventory",
  "net.minecraft.world.inventory.AbstractContainerMenu",
  "net.minecraft.world.inventory.MenuType",
  "net.minecraft.world.inventory.Slot",
  "net.minecraft.world.inventory.ClickType",
  "net.minecraft.nbt.CompoundTag",
  "net.minecraft.world.item.component.CustomData",
  "net.minecraft.world.inventory.CraftingMenu",
  "net.minecraft.world.inventory.ChestMenu",
  "net.minecraft.world.inventory.AnvilMenu",
  "net.minecraft.world.inventory.ContainerLevelAccess",
  "net.minecraft.world.entity.ai.attributes.AttributeInstance",
  "net.minecraft.world.effect.MobEffectCategory",
  "net.minecraft.world.item.trading.Merchant",
  "net.minecraft.world.item.trading.MerchantOffer",
  "net.minecraft.world.item.trading.MerchantOffers",
  "net.minecraft.world.item.trading.ItemCost",
  "net.minecraft.tags.TagKey",
  "net.minecraft.world.entity.ai.attributes.Attribute",
  "java.util.Optional",
  "net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents",
  "net.fabricmc.fabric.api.item.v1.DefaultItemComponentEvents",
  "net.minecraft.core.component.DataComponentMap",
  "net.minecraft.world.item.component.ItemAttributeModifiers",
  "net.minecraft.world.entity.ai.attributes.AttributeModifier",
  "net.minecraft.world.entity.EquipmentSlotGroup",
  "net.minecraft.server.MinecraftServer",
  "net.minecraft.server.level.ServerLevel",
  "net.minecraft.server.level.ServerPlayer",
  "net.minecraft.server.permissions.LevelBasedPermissionSet",
  "net.minecraft.sounds.SoundEvent",
  "net.minecraft.sounds.SoundEvents",
  "net.minecraft.sounds.SoundSource",
  "net.minecraft.tags.BlockTags",
  "net.minecraft.tags.ItemTags",
  "net.minecraft.util.Mth",
  "net.minecraft.util.RandomSource",
  "net.minecraft.util.valueproviders.IntProvider",
  "net.minecraft.util.valueproviders.UniformInt",
  "net.minecraft.world.InteractionHand",
  "net.minecraft.world.InteractionResult",
  "net.minecraft.world.damagesource.DamageSource",
  "net.minecraft.world.damagesource.DamageSources",
  "net.minecraft.world.effect.MobEffect",
  "net.minecraft.world.effect.MobEffectInstance",
  "net.minecraft.world.effect.MobEffects",
  "net.minecraft.world.entity.Entity",
  "net.minecraft.world.entity.EntitySpawnReason",
  "net.minecraft.world.entity.EntityType",
  "net.minecraft.world.entity.EquipmentSlot",
  "net.minecraft.world.entity.LightningBolt",
  "net.minecraft.world.entity.LivingEntity",
  "net.minecraft.world.entity.Mob",
  "net.minecraft.world.entity.item.ItemEntity",
  "net.minecraft.world.entity.ai.attributes.Attributes",
  "net.minecraft.world.entity.player.Player",
  "net.minecraft.world.entity.projectile.hurtingprojectile.SmallFireball",
  "net.minecraft.world.food.FoodProperties",
  "net.minecraft.world.item.BlockItem",
  "net.minecraft.world.item.CreativeModeTab",
  "net.minecraft.world.item.Item",
  "net.minecraft.world.item.ItemStack",
  "net.minecraft.world.item.Items",
  "net.minecraft.world.item.Rarity",
  "net.minecraft.world.item.ToolMaterial",
  "net.minecraft.world.item.TooltipFlag",
  "net.minecraft.world.item.component.TooltipDisplay",
  "net.minecraft.world.item.context.UseOnContext",
  "net.minecraft.world.item.equipment.ArmorMaterial",
  "net.minecraft.world.item.equipment.ArmorMaterials",
  "net.minecraft.world.item.equipment.ArmorType",
  "net.minecraft.world.level.ClipContext",
  "net.minecraft.world.level.Level",
  "net.minecraft.world.level.block.Block",
  "net.minecraft.world.level.block.Blocks",
  "net.minecraft.world.level.block.DropExperienceBlock",
  "net.minecraft.world.level.block.SoundType",
  "net.minecraft.world.level.block.entity.BlockEntity",
  "net.minecraft.world.level.block.state.BlockBehaviour",
  "net.minecraft.world.level.block.state.BlockState",
  "net.minecraft.world.level.levelgen.GenerationStep",
  "net.minecraft.world.level.levelgen.placement.PlacedFeature",
  "net.minecraft.world.level.storage.LevelResource",
  "net.minecraft.world.phys.AABB",
  "net.minecraft.world.phys.BlockHitResult",
  "net.minecraft.world.phys.EntityHitResult",
  "net.minecraft.world.phys.HitResult",
  "net.minecraft.world.phys.Vec3",
  "net.fabricmc.fabric.api.client.rendering.v1.hud.HudElementRegistry",
  "net.fabricmc.fabric.api.client.rendering.v1.hud.HudElement",
  "net.fabricmc.fabric.api.client.rendering.v1.hud.VanillaHudElements",
];

/** Yarn 名 → Mojang 名 (import / 参照のエラーメッセージで案内する) */
export const YARN_TO_MOJ: Record<string, string> = {
  ...CLASS_MAP,
  PlayerEntity: "Player",
  MinecraftClient: "Minecraft",
  ClientPlayerEntity: "LocalPlayer",
  Items: "Items",
  Blocks: "Blocks",
  ItemStack: "ItemStack",
  ToolMaterials: "ToolMaterial",
  ArmorItem: "Item.Properties#humanoidArmor",
  SwordItem: "Item.Properties#sword",
  PickaxeItem: "Item.Properties#pickaxe",
  AxeItem: "Item.Properties#axe",
  ShovelItem: "Item.Properties#shovel",
  DrawContext: "GuiGraphics",
  KeyBinding: "KeyMapping",
  InputUtil: "InputConstants",
  PacketCodec: "StreamCodec",
  PacketCodecs: "ByteBufCodecs",
  CustomPayload: "CustomPacketPayload",
  RegistryByteBuf: "RegistryFriendlyByteBuf",
  ServerCommandSource: "CommandSourceStack",
  MinecraftServer: "MinecraftServer",
  RegistryKey: "ResourceKey",
  RegistryKeys: "Registries",
  TooltipType: "TooltipFlag",
  ItemGroups: "CreativeModeTabs",
  EntityAttributes: "Attributes",
  BlockState: "BlockState",
  SimpleParticleType: "SimpleParticleType",
  MathHelper: "Mth",
  Random: "RandomSource",
  Direction: "Direction",
};

export const MOJ_PITFALLS: { re: RegExp; message: string; severity: "error" | "warning"; code: string }[] = [
  { re: /^ResourceLocation$/, message: "`ResourceLocation` は 1.21.11 で `Identifier` に改名されました (net.minecraft.resources.Identifier)", severity: "error", code: "MC-RENAMED" },
  { re: /^Minecraft$/, message: "クライアント専用クラスです。専用サーバーで NoClassDefFoundError になります (サーバー側コードでは使用不可)", severity: "error", code: "MC-CLIENT-ONLY" },
  { re: /^LocalPlayer$/, message: "クライアント専用クラスです。サーバー側コードでは使用できません", severity: "error", code: "MC-CLIENT-ONLY" },
  { re: /^(SwordItem|PickaxeItem|AxeItem|ShovelItem|HoeItem|ArmorItem|ToolItem|MiningToolItem)$/, message: "1.21.2 以降、道具・防具は専用クラスではなく `Item.Properties().sword()/pickaxe()/humanoidArmor()` で作ります", severity: "error", code: "MC-ITEM-PROPS" },
  { re: /^InteractionResultHolder$/, message: "`InteractionResultHolder` は 1.21.2 で廃止されました。`Item.use` は `InteractionResult` を直接返します", severity: "error", code: "MC-USE-RESULT" },
];
